### ISSUE TITLE
[BUG] Discord doesn't show preview for the generated videos

### ISSUE THREAD

**Issue by Eddio0141** [dec05eba/gpu-screen-recorder-issues#13]
**Describe the bug**
Any recording made by gpu-screen-recorder uploaded to discord doesn't generate a preview, even if `-fm cfr` is set

**To Reproduce**
`gpu-screen-recorder -w DP-3 -c mp4 -f 60 -a "alsa_output.usb-Kingston_HyperX_Cloud_II_Wireless_000000000001-00.analog-surround-71.monitor" -fm cfr -o /mnt/hdd/Videos/replay/test.mp4`

**Expected behavior**
Usable video for discord

**Screenshots**
![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/31967258/3d78647e-9619-414e-8ef9-62b9c98fdca0)
![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/31967258/35e68ee0-7f8d-4388-91b7-d26a860d285d)

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: swayfx
 - Distro: NixOS
 - GPU: AMD RX 6700 XT
 - Version: 2023-11-18 build, from nix packages unstable

**Additional context**
- This is the actual video that isn't processed through ffmpeg: [link](https://cdn.discordapp.com/attachments/904644896755957790/1230303615944626196/test.mp4?ex=6632d487&is=66205f87&hm=234af76a4a49b1d6e1f3b58ab918c8e3158d2cf5185b94481c2e819c2ec879e3&)
- Video runs fine on mpv, its just discord not accepting it
- Obs produces videos that I can directly use on discord
- Passing it through ffmpeg would make the video usable on discord: `ffmpeg -i /mnt/hdd/Videos/replay/test.mp4 output.mp4`, but I have to use it without `-c copy`, and that takes a while to do

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
You have to record it with h264 codec using the -k h264 option. Discord doesn't support hevc (which is the default in gpu screen recorder). It's mentioned in FAQ: https://git.dec05eba.com/gpu-screen-recorder/about/

**Comment by Eddio0141** [comment]
Right I somehow missed that, thanks
