### ISSUE TITLE
[BUG] Weird Colors on the right of the screen after recording & watching video

### ISSUE THREAD

**Issue by z5vix** [dec05eba/gpu-screen-recorder-issues#16]
**Describe the bug**
When recording, on the right side of the screen. im getting some weird color, im unsure how this happens exactly except that its only showing only on the GPU, using H264 works as expected

**To Reproduce**
Record with a gpu 

**Expected behavior**
they arent suppost to be there

**Screenshot**
![Screenshot_20240501_233029](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/90941565/84c9b4b4-ae1c-4738-b34b-0ca0d9b0acb0)

 
 - both X11 and Wayland
- Desktop environment/Window Manager: KDE
 - Distro: Nobara 39 KDE
 - GPU: "STG" RX 580 2048SP
 - Version: 3.7.2 4/19/24

**Additional context**
everything has been explained, this hasnt happened on any version prior to 3.7.2 at least i believe so.

- [x] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
You didn't include drm_info output which is part of the report template. Please do so.

Also you can test if it does happen in older gpu screen recorder version by running `sudo flatpak update --system --commit=7b42065ffa5b3d2a8c9aa53f426b60eb2a5f9e909b277d1ab5ee4bdd3297e6e0 com.dec05eba.gpu_screen_recorder` to downgrade it and then try recording with hevc again.

But I believe it's unrelated to gpu screen recorder itself, or at least not a new issue.
You can try downgrading mesa in the flatpak to see if it's an amd driver issue instead, run: `sudo flatpak update --system --commit=8dc61a1d337706a71392fec507039dabca96ce29f9e068ee867156482db7c856 org.freedesktop.Platform.GL.default/x86_64/23.08` and try recording with hevc again.

Also can you upload a video that shows the issue? just record 3-5 seconds of video and upload it raw (without editing it).

**Comment by z5vix** [comment]
your right, it doesnt seem to be GSR itself. as downgrading did not solve the problem.
im using 1360 x 768 TV which is like, not 1080p but not 720p either the recorded video is outputted as 720p 

**Video1 Downgraded**
https://github.com/dec05eba/gpu-screen-recorder-issues/assets/90941565/f4056399-72bb-406b-b751-be4cb9dd12fb

**Video2 Downgraded, Older Mesa **
https://github.com/dec05eba/gpu-screen-recorder-issues/assets/90941565/afe2f2b9-be11-4256-96bc-f06249767cc3
 
 im not exactly sure what drm_info is so i just ran it through the terminal and im just going to upload a copy pasted text of that 
[drm_info?.txt](https://github.com/dec05eba/gpu-screen-recorder-issues/files/15197007/drm_info.txt)

**Comment by z5vix** [comment]
**Downgraded, Older Mesa** 

https://github.com/dec05eba/gpu-screen-recorder-issues/assets/90941565/afda197b-8b33-41b2-a2c5-94e3f901d44f



**Updated, Older Mesa**

https://github.com/dec05eba/gpu-screen-recorder-issues/assets/90941565/3998b155-e1c1-4d9b-b9fc-90d063e0bda1

**Comment by dec05eba** [comment]
I can reproduce it at that resolution and the same thing happens in obs studio when using vaapi. It's a ffmpeg bug and amd driver bug. av1 has the same issue except with av1 it's a hardware bug that cant be fixed.
It happens at very low resolutions and uncommon resolutions more.
