### ISSUE TITLE
[BUG] Failed to find H264/HVEC video codecs.

### ISSUE THREAD

**Issue by OverStyleFR** [dec05eba/gpu-screen-recorder-issues#17]
**Describe the bug**
The software don't want to start because of "missing video codec".

**To Reproduce**
Launch GPU Screen Recorder

**Screenshots**
Screenshots :
![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/94577363/df18bf66-f75d-4ed0-ac78-fd126fedbaea)

**Desktop (please complete the following information):**
 - X11
- Desktop environment
 - Distro: Debian 12 (bookworm)
 - GPU: RTX 2080 FE TI
 - Version: 3.7.2 flatpak

**Additional context**
Add any other context about the problem here, such as terminal output of running GPU Screen Recorder and if there was an issue in the video then run the command `sudo drm_info > log.log` and attach that log.log file in this bug report. drm_info can be installed from your package manager or from https://gitlab.freedesktop.org/emersion/drm_info.

> I can't use the 'drm_info' command. I installed it, but don't work.

**Comment by OverStyleFR** [comment]
I installed the driver with the `.run` of nvidia driver.

That's a output of my information from steam :

```

Computer Information:
Manufacturer: Gigabyte Technology Co., Ltd.
Model: B660 GAMING X DDR4
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: 13th Gen Intel(R) Core(TM) i7-13700K
CPU Family: 0x6
CPU Model: 0xb7
CPU Stepping: 0x1
CPU Type: 0x0
Speed: 5300 MHz
24 logical processors
16 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Debian GNU/Linux 12 (bookworm) (64 bit)
Kernel Name: Linux
Kernel Version: 6.1.0-20-amd64
X Server Vendor: The X.Org Foundation
X Server Release: 12101007
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20240304.79797
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 550.78
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x10de
DeviceID: 0x1e07
Revision Not Detected
Number of Monitors: 4
Number of Logical Video Cards: 2
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 7680 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 11264 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: %1$s
Memory:
RAM: 64060 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 936330 MB
Largest Free Hard Disk Block: 622599 MB
Storage:
Number of SSDs: 5
SSD sizes: 1000G,1000G,512G,512G,500G
Number of HDDs: 0
Number of removable drives: 0

```

**Comment by dec05eba** [comment]
Run `flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 60 -o video.mp4` in a terminal and post the output. That may contain more information why your gpus encoder fails to load.
But besides that, it sounds like a flatpak issue, probably related to you installing nvidia .run manually so you should ask about it in a flatpak support channel.

**Comment by OverStyleFR** [comment]
```sh
tomv@NZXT-2024-DebianKDE ~ 💻$ flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 60 -o video.mp4
[hevc_nvenc @ 0x55b5df87fb00] ignoring invalid SAR: 0/0
[hevc_nvenc @ 0x55b5df87fb00] dl_fn->cuda_dl->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
Info: using h264 encoder because a codec was not specified and your gpu does not support hevc
[h264_nvenc @ 0x55b5df87fb00] ignoring invalid SAR: 0/0
[h264_nvenc @ 0x55b5df87fb00] dl_fn->cuda_dl->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
Error: your gpu does not support 'h264' video codec. If you are sure that your gpu does support 'h264' video encoding and you are using an AMD/Intel GPU,
  then make sure you have installed the GPU specific vaapi packages (intel-media-driver, libva-intel-driver or libva-mesa-driver).
  It's also possible that your distro has disabled hardware accelerated video encoding for 'h264' video codec.
  This may be the case on corporate distros such as Manjaro, Fedora or OpenSUSE.
  You can test this by running 'vainfo | grep VAEntrypointEncSlice' to see if it matches any H264/HEVC profile.
  On such distros, you need to manually install mesa from source to enable H264/HEVC hardware acceleration, or use a more user friendly distro. Alternatively record with AV1 if supported by your GPU.
  You can alternatively use the flatpak version of GPU Screen Recorder (https://flathub.org/apps/com.dec05eba.gpu_screen_recorder) which bypasses system issues with patented H264/HEVC codecs.
  Make sure you have mesa-extra freedesktop runtime installed when using the flatpak (this should be the default), which can be installed with this command:
  flatpak install --system org.freedesktop.Platform.GL.default//23.08-extra
```

**Comment by OverStyleFR** [comment]
Not the first time that i have some trouble with decoder/encoder things since i installed the drivers manually

**Comment by dec05eba** [comment]
Ok so it's actually an issue with cuda. Im guessing there is some weird thing going on with the flatpak nvidia version since with nvidia it has to match your system driver version. You could try running `flatpak update` to see if that fixes it or manually installing the flatpak nvidia driver version that matches your system nvidia driver version. Maybe your system nvidia driver is too new. Otherwise ask in the flatpak support channels if you can find the place. It's not really something I can help with.

**Comment by dec05eba** [comment]
It seems like this issue can happen if your nvidia driver (and nvidia utils or whatever its called on debian that installs the cuda package) doesn't match your kernel version

**Comment by OverStyleFR** [comment]
> It seems like this issue can happen if your nvidia driver (and nvidia utils or whatever its called on debian that installs the cuda runtime library / nvenc) doesn't match your kernel version

How i can check that ?

**Comment by dec05eba** [comment]
I dont really know, it's just something I've heard before when you install the driver manually. Didn't the install script give a warning about that? or dmesg.
