### ISSUE TITLE
[BUG] AMD GPU fails to detect H264/HEVC

### ISSUE THREAD

**Issue by VelamyGH** [dec05eba/gpu-screen-recorder-issues#18]
**Describe the bug**
Flatpak version of the GTK version gives the error (screenshot) while the package it is asking me for is already installed on my system.

**To Reproduce**
Open latest GUI version installed from flathub with the correct packages installed

**Expected behavior**
Application opens without the encoder missing error

**Screenshots**
![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/48131627/c2b47fe4-ffe2-4694-8e21-faa7cbcbc1ef)
![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/48131627/6d145f93-8d8a-4741-a9af-1352c1bc3570)

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: KDE 6
 - Distro: Arch
 - GPU: AMD RX6500 XT
 - Version: (latest flatpak version, aur or source) flatpak gui/gtk

**Additional context**
I know for a fact that they work because OBS can open for me just fine. Would prefer to use this though as it looks very promising and easy to use compared to the built in replay option in OBS. Thanks in advance :)

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
Run gpu screen recorder from the terminal and post the output: `flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 60 -o video.mp4`

**Comment by dec05eba** [comment]
Also run `ls -lah /dev/dri/by-path` and post the output and also the output of `vainfo`.

**Comment by dec05eba** [comment]
Or actually, according to amd website your gpu doesn't support hardware accelerated video encoding: https://www.amd.com/en/products/graphics/amd-radeon-rx-6500-xt so when you are using obs you aren't using your gpu to encode.

**Comment by VelamyGH** [comment]
i see, thanks for clarifying
