### ISSUE TITLE
[FEAT] VP9 Codec Support

### ISSUE THREAD

**Issue by BrycensRanch** [dec05eba/gpu-screen-recorder-issues#19]
### Proposal
Adding VP9 support to GPU Screen Recorder. This would give you an output format that is compatible with Discord and other platforms alike since YouTube uses VP9 alongside AV1 and other codecs. This feature would significantly enhance the software's utility especially for users like me where our hardware can do VP9 but *can't* do AV1. It's the next best thing for videos going to the great interwebs.

https://imagekit.io/blog/vp9-codec/

I am aware you likely don't use Discord considering you don't even use GitHub to host your project's source code anymore.

**Comment by dec05eba** [comment]
This is not where you request for features as mentioned in the README: `This is only for reporting issues, not for developing GPU Screen Recorder or suggesting features.`. I dont accept feature requests. Also VP9 is already planned but I dont have any hardware that supports it.
