### ISSUE TITLE
[BUG] Rhythmic stutter after changing workspace and back to game

### ISSUE THREAD

**Issue by Nama** [dec05eba/gpu-screen-recorder-issues#2]
**Describe the bug**
After changing from the workspace the game is on to another workspace and back (might take a few tries/minutes), the game stutters periodically.

**To Reproduce**
`gpu-screen-recorder -w DP-3 -f 60 -q medium -r 20 -k h264 -c mp4 -ac aac -a "$(pactl get-default-sink).monitor" -o /tmp -v no -sc scripts/clip_upload.sh`
This happens on sway and hyprland. On every game I played so far (Proton games: Overwatch, Helldivers II)
After killing the `gpu-screen-recorder` process, the stutters go away, else they don't seem to stop.

**Expected behavior**
No stutters

**Screenshots**
Recorded with gpu-screen-recorder: https://streamable.com/v2altf
screen recording in slowmotion from 144Hz: https://gitlab.freedesktop.org/drm/amd/uploads/f301d4e6ab3dcd0ffe4e89ecf47d3acb/ow.mp4 (from the [AMD repo issue](https://gitlab.freedesktop.org/drm/amd/-/issues/3240))
Screen recording was actual in-game footage, no recorded video.
(both too big to upload here)

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: Sway and hyprland
 - Distro: Arch
 - GPU: RX 7900 XT
 - Version: aur

**Additional context**
I couldn't record these stutters with OBS, but gpu-screen-recorder seems to record them.  
I have this issue for a long time now and [thought its a driver](https://gitlab.freedesktop.org/drm/amd/-/issues/3240) issue >_<  
Couldn't reproduce on desktop only
[drm_info](https://github.com/dec05eba/gpu-screen-recorder-issues/files/14859367/log.log)
Output always starts with this. There is no output as the stuttering starts.

> [h264_vaapi @ 0x5646698fb280] ignoring invalid SAR: 0/0
> [h264_vaapi @ 0x5646698fb280] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
> gsr info: gsr_kms_client_init: waiting for server to connect
> kms server info: connecting to the client
> gsr info: gsr_kms_client_init: server connected
> gsr info: replacing file-backed unix domain socket with socketpair
> kms server info: connected to the client
> gsr info: using socketpair
> [h264_vaapi @ 0x5646698fb280] ignoring invalid SAR: 0/0
> [h264_vaapi @ 0x5646698fb280] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
When you record with OBS are you recording with vaapi video encoder enabled? try doing that to see if you have the same issue. Also try recording with hevc codec in gpu screen recorder to see if there is a difference. I have a rx 7800xt and I cant reproduce this issue myself so it might be an issue specifically with 7900 xt.

**Comment by Nama** [comment]
> When you record with OBS are you recording with vaapi video encoder enabled? try doing that to see if you have the same issue.

Yes. I tried again now with these settings. The game didn't stutter.
![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/2297270/09dd8f24-99e1-4cff-9271-6b7e7f9518dc)

> Also try recording with hevc codec in gpu screen recorder to see if there is a difference.

Seems like its making a difference! Didn't get the stutters with hevc :O
Hopefully it wont just take longer or something. I'll change the command and we'll see...
Saving clips as hevc wouldn't be too bad, since I started to process the clips with ffmpeg to optimize them for web (`-movflags +faststart`) for faster playback in the browser.
(Would that be possible to directly save them like that, or is that an hardware limitation?)

> Also have you tested if this issue happens when recording a regular video, not replay?

Just did, yes.

**Comment by dec05eba** [comment]
I dont know if hevc working with no issue is a false positive or not, it may just not have the issue right now. I dont know how often it happened to you. The only extra thing that gpu screen recorder uses for h264 vaapi config that differs from yours on obs is that coder "cabac" is used and quality is set to 5.
About the faststart I did consider it around 2 years ago but I didn't do it, I dont remember why. Maybe it didn't work with hardware encoders. It's still in the TODO list. I'll try enabling it sometime.

**Comment by Nama** [comment]
> I dont know if hevc working with no issue is a false positive or not, it may just not have the issue right now. I dont know how often it happened to you.

Generally happens mostly after being on a different workspace for 3-5 minutes (and sometimes faster). Rarely I need to be on another workspace for 10 or more minutes.

> The only extra thing that gpu screen recorder uses for h264 vaapi config that differs from yours on obs is that quality is set to 5. Obs seems to not use that option at all.

You don't mean `QP` I assume, since that would be absurdly high quality.

> About the faststart I did consider it around 2 years ago but I didn't do it, I dont remember why. Maybe it didn't work with hardware encoders.

I do it with vaapi and it seems to work:
`ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format vaapi -loglevel quiet -i $clip_o -preset fast -threads 16 -movflags +faststart -qp 31 -vcodec h264_vaapi -c:a copy $local_folder$clip`

**Comment by dec05eba** [comment]
> You don't mean `QP` I assume, since that would be absurdly high quality.
No i meant "quality", as this says: ffmpeg -h encoder=h264_vaapi. Maybe I should remove it. Can you try using that in obs to see if it triggers the issue? maybe that can be done by adding `-quality 5` to that FFmpeg options at the bottom on that settings page.
> I do it with vaapi and it seems to work: `ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format vaapi -loglevel quiet -i $clip_o -preset fast -threads 16 -movflags +faststart -qp 31 -vcodec h264_vaapi -c:a copy $local_folder$clip`
Thanks, i'll add that then if there aren't any downsides

**Comment by Nama** [comment]
> Can you try using that in obs to see if it triggers the issue?

Didn't trigger it in the "short" test I just did.

> Thanks, i'll add that then if there aren't any downsides

Thank you!
I didn't notice any downsides and as far as I know, it just moves the meta data without tinkering with the quality.
A switch to enable would work, too.

**Comment by dec05eba** [comment]
Actually I think I know what it can be. Can you try using the flatpak version instead with the same h264 command? the that would be: `flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w DP-3 -f 60 -q medium -r 20 -k h264 -c mp4 -ac aac -a "$(pactl get-default-sink).monitor" -o /tmp -v no -sc ./scripts/clip_upload.sh`

**Comment by Nama** [comment]
Still happening.

**Comment by dec05eba** [comment]
I updated gpu-screen-recorder on aur with a test change, can you update and try again with h264 codec?

**Comment by Nama** [comment]
The issue seems to be fixed, thank you very much!

I let a recording running then the replay, both for half an hour with the game in the background and no stutters so far.
Would have appeared until now.

**Comment by dec05eba** [comment]
The fix is h264 specific (the option that was set doesn't exist for hevc). Thanks for testing!

**Comment by Nama** [comment]
That sounds awful... Thanks for going thru all that D:

Is [this](https://git.dec05eba.com/gpu-screen-recorder/commit/?id=6770bac05b39f930db40c50dcb969685cf821e2b) really the fix and not the first attempt with the flatpak?

**Comment by dec05eba** [comment]
Yes xd
