### ISSUE TITLE
[BUG] 3440x1440 resolution cuts off right of screen recording

### ISSUE THREAD

**Issue by richardtatum** [dec05eba/gpu-screen-recorder-issues#21]
**Describe the bug**
Videos produced when using a 3440x1440 resolution causes the right X number of pixels to be cut off/distorted.

**To Reproduce**
Running with systemd at startup
`/bin/sh -c 'AUDIO="${AUDIO_DEVICE:-$(pactl get-default-sink).monitor}"; gpu-screen-recorder -v no -w $WINDOW -c $CONTAINER -q $QUALITY -k $CODEC -ac $AUDIO_CODEC -a "$AUDIO" -f $FRAMERATE -r $REPLAYDURATION -o "$OUTPUTDIR" -mf $MAKEFOLDERS $ADDITIONAL_ARGS -cr $COLOR_RANGE'`

Output of `gpu-screen-recorder.env`:
```
WINDOW=screen
CONTAINER=mp4
QUALITY=very_high
CODEC=auto
AUDIO_CODEC=opus
FRAMERATE=60
REPLAYDURATION=60
OUTPUTDIR=/home/rt/Videos/replays
MAKEFOLDERS=no
COLOR_RANGE=limited
```

**Expected behavior**
The recording to capture the full 3440x1440 resolution

**Screenshots**
Below is a screenshot of a recording, played back with MPV:

![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/46816684/2fd5549f-a01f-42b7-a54d-69842f033dcd)

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: SwayWM
 - Distro: Arch
 - GPU: AMD RX6800XT
 - Version: Latest AUR gpu-screen-recorder-git, r588.133c3a2-

**Additional context**
Does not happen if I use OBS.

- [x] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
It might be the amd driver bug mentioned in the FAQ: https://git.dec05eba.com/gpu-screen-recorder/about/ (https://gitlab.freedesktop.org/mesa/mesa/-/issues/10985). Try recording with h264 codec and see if it happens.

**Comment by dec05eba** [comment]
I added a custom mode for 3440x1440 to my display and tested it and h264 fixes this issue, so it is that same amd driver bug. The fix was merged 1 month ago in the amd driver and the ffmpeg fix was merged recently too, so this issue should fix itself when arch gets the updates.

**Comment by dec05eba** [comment]
This issue hasn't been fixed in ffmpeg yet but I made a workaround for now. The right side is black now instead of that glitched graphics and it moves the video to the center so its less space that appears cut off.
