### ISSUE TITLE
GTK front end is using old libappindicator

### ISSUE THREAD

**Issue by 3vi1** [dec05eba/gpu-screen-recorder-issues#23]
I'm not sure if this is a problem for other distros yet, but the Ubuntu Oracular Oriole (24.10) development repos have migrated from libappindicator3-1 to the newer libayatana-appindicator3-1.  The packages conflict, so you can't have both installed.

```
Building gui...
src/main.cpp:24:10: fatal error: libappindicator/app-indicator.h: No such file or directory
   24 | #include <libappindicator/app-indicator.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

As Ayatana is backwards compatible, I was able to get it to compile with the newer library by doing the following:
* Change the include in the error above to "#include <libayatana-appindicator/app-indicator.h>"
* Remove -Werror from the opts in build.sh so that the deprecated functions don't stop the compile.
* In the dependencies, replace appindicator3-0.1 with ayatana-appindicator3-0.1

It might be a good idea to make these conditional if possible - preferring Ayatana, but falling back to appindicator on older distros.

Thanks for your hard work on this cool utility!

**Comment by dec05eba** [comment]
Thanks for telling me that. On arch linux I dont even have libayatana-appindicator installed so it seems like most applications still use libappindicator on arch. I wonder which one is easiest available in flatpaks.

**Comment by dec05eba** [comment]
Can you pull the latest changes and try if it works on ubuntu? thanks

**Comment by 3vi1** [comment]
Yep - pulled, built clean, installed, and the tray icon is working fine.  Thanks!
