### ISSUE TITLE
[BUG] Record in VFR?

### ISSUE THREAD

**Issue by HeroponRikiBestest** [dec05eba/gpu-screen-recorder-issues#26]
**Describe the bug**
This probably isn't a bug, but either just me misunderstanding something, or asking for something that isn't supported.
I am recording a game that I will not be able to run at fullspeed. The gameplay footage will obviously then vary heavily in framerate throughout the recording. I wanted to record the video in VFR so that there are no duplicate frames. While gpu-screen-recorder supports vfr for recording, it still makes you choose a constant framerate via `-f`. As is, I need to re-encode after recording via `ffmpeg -i video.mkv -vf mpdecimate -vsync vfr output.mkv` to achieve what I want. Is it possible to record footage natively in VFR?

**To Reproduce**
Attempt to record any video; -f is required.

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: Mutter (Muffin)
 - Distro: Linux Mint 21.3
 - GPU: AMD Ryzen 4750U Pro (iGPU)
 - Version: (latest flatpak version, aur or source)  Source (https://git.dec05eba.com/gpu-screen-recorder/commit/?id=3e2e2444d9fa65ae404604542689cf7829c99cfa)

**Comment by dec05eba** [comment]
The framerate (-f) you set with vfr is the max fps and just the "reported" fps of the video that has no effect on the video itself. Its not the actual fps and it doesn't duplicate frames so you shouldn't need to re-encode the video.

**Comment by dec05eba** [comment]
The framerate that you set with `-f` in vfr mode is the max framerate allowed. If your recording fps drops below that then it will stay below that in those times without trying to duplicate the frames (unlike in cfr that will try to duplicate frames to match `-f`). So it should already work like you expect without having to re-encode the video.

**Comment by dec05eba** [comment]
I clearified the behavior a bit now when you run gpu-screen-recorder --help

**Comment by HeroponRikiBestest** [comment]
If I don't re-encode with ffmpeg, it's at 60 FPS regardless of game framerate. Ultimately, in that case, I guess the game itself probably updates the display ever 60 frames or something, even if it's clearly running below that.

**Comment by dec05eba** [comment]
oh then it's a different feature you want. You want recording to match the game fps?

**Comment by HeroponRikiBestest** [comment]
Ahhh, gotcha. Yeah, that's what I was requesting. 
Just for confirmation:
Recording (via `./gpu-screen-recorder -w 174063619 -a "$(pactl get-default-sink).monitor" -o m.mkv -fm vfr -f 60`)

[m.webm](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/50224630/be2a642a-832b-40ee-a31c-c13f61b43c00)

Reencoding via `ffmpeg -i m.mkv -vf mpdecimate -vsync vfr output.mkv`


https://github.com/dec05eba/gpu-screen-recorder-issues/assets/50224630/c5e4343b-acd6-4ea4-88d9-a75757fa13f3

**Comment by dec05eba** [comment]
Oh ok I see, so the game is limited in performance by the cpu? but yeah this functionality is not supported right now. I will consider adding it sometime in the future.

**Comment by HeroponRikiBestest** [comment]
No, the game is limited in performance by the GPU. The CPU isn't anywhere close to being maxed on any thread. Anyways, if recording matching game FPS isn't supported, understandable.

**Comment by HeroponRikiBestest** [comment]
Also, where did I say this was the case with the flatpak version? I stated in the initial post that this was tested from source, not flatpak.

**Comment by dec05eba** [comment]
Oh ok I misunderstood. But yes, with the flatpak version it should behave as you expected here as a side effect of how the amd driver works.

**Comment by HeroponRikiBestest** [comment]
Oh, huh, gotcha, I'll try it. If possible, is there any way for me to get identical functionality when building from source? Whether that be by different compile options, environment settings when building, etc.

**Comment by dec05eba** [comment]
`sudo setcap -r $(which gpu-screen-recorder)` should do that

**Comment by dec05eba** [comment]
how did you install gpu screen recorder to begin with? it seems like you haven't installed it the normal way

**Comment by dec05eba** [comment]
> Had to change the command to `sudo setcap -r gpu-screen-recorder` since this is just a binary I built.

i dont know how you installed it but sure, as long as `getcap gpu-screen-recorder` doesn't say `cap_sys_nice=ep` then it should work

**Comment by HeroponRikiBestest** [comment]
Oh, right- I had to build via meson, I think the install script might've had issues? I don't remember why I had to build via meson, sorry.

**Comment by dec05eba** [comment]
That error is a bug in the old linux mint version of setcap, it means that it had no effect since it didn't do anything (since you likely didn't install gpu-screen-recorder and only built it instead). Try running `getcap gpu-screen-recorder` to see what it says.

**Comment by HeroponRikiBestest** [comment]
`getcap gpu-screen-recorder` doesn't produce any output.

**Comment by dec05eba** [comment]
ok then that setcap command is not needed. But hmm, I guess the thing I mentioned wont work for you so for now you will have to re-encode the video. But also the video framerate does actually drop below 60 in the video you posted, it drops down to 25 at one point but it doesn't match the games fps exactly yeah.

**Comment by dec05eba** [comment]
btw, what is the exact command you use to record the game with?

**Comment by HeroponRikiBestest** [comment]
`./gpu-screen-recorder -w 174063619 -a "$(pactl get-default-sink).monitor" -o m.mkv -fm vfr -f 60`

**Comment by dec05eba** [comment]
@HeroponRikiBestest I added a new option `-fm content`, can you try it? it currently only works with window capture (the way you are capturing right now) and it should match the recording fps to the game fps (when the window content updates).

**Comment by HeroponRikiBestest** [comment]
Awesome, works great as far as I can tell! Thank you so much for adding this, works exactly like I was hoping.

[m.mkv.zip](https://github.com/user-attachments/files/15938264/m.mkv.zip)

As for your latter note, afaik I can't meson install because there are some other issues with my meson setup that I still never figured out.

**Comment by HeroponRikiBestest** [comment]
Also, curious; will support eventually be added for other options besides window capture? If not, understandable, was just wondering.

**Comment by dec05eba** [comment]
Monitor capture on x11 yes. It's not possible on wayland yet, but maybe it will be when pipewire support is added.
