### ISSUE TITLE
[BUG] Mismatched libavcodec versions on Arch

### ISSUE THREAD

**Issue by git-iso** [dec05eba/gpu-screen-recorder-issues#28]
**Describe the bug**
ffmpeg provides libavcodec ver. 61 on Arch repos, program demands ver. 60.

**To Reproduce**
1. Compile gpu-screen-recorder from AUR
2. Run command `gpu-screen-recorder --help`
3. Get error: `gpu-screen-recorder: error while loading shared libraries: libavcodec.so.60: cannot open shared object file: No such file or directory`

**Screenshots**
![2024-06-21_21-11](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/46284404/ca943eef-4a62-4dfa-b589-5dd9469e0bb3)

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: KDE Plasma 6.1
 - Distro: Arch Linux
 - GPU: NVIDIA RTX 3060 TI
 - Version: AUR

**Comment by dec05eba** [comment]
The program doesn't use any specific version of ffmpeg libraries. You get this issue when you update ffmpeg without re-compiling gpu screen recorder. Try reinstalling gpu-screen-recorder-git.

**Comment by dec05eba** [comment]
But I see that ffmpeg 7 broke gpu screen recorder so I'll have to fix that.

**Comment by dec05eba** [comment]
I fixed the issues that ffmpeg 7 introduced now.
