### ISSUE TITLE
[BUG] Screen tearing

### ISSUE THREAD

**Issue by Korgen1** [dec05eba/gpu-screen-recorder-issues#29]
**Describe the bug**

When running gpu-screen-recorder (specifically tested on deep rock galactic if its relevant) there is pretty bad screen tearing, normally I would get this screen tearing when I have vsync disabled in the game settings, however when using gpu-screen-recorder I get the screen tearing even with vsync on.

**To Reproduce**
The GPU Screen Recorder command you ran or if you used the GUI version then describe which options you used.

ENV Options:
WINDOW = focused
CONTAINER = mp4
QUALITY = very_high (lowering the quality doesn't seem to fix the issue)
CODEC = h264
AUDIO_CODEC = opus
AUDIO_DEVICE = (my audio devices)
FRAMERATE = 60
REPLAYDURATION = 60
COLOR_RANGE=full
OUTPUTDIR = (directory)
Restart=on-failure

**Screenshots**

Can't screenshot as the issue doesn't appear well in the actual recordings, but it is very obvious on my monitor

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: Gnome
 - Distro: Manjaro
 - GPU: RTX 4060
 - Version (latest flatpak version, aur or source): AUR

**Additional context**

My GPU is not being stressed at all during the recordings (sits around 30% usage in game), but just enabling gpu-screen-recorder is enough to make the game unplayable with how much screen-tearing appears. Should be mentioned that it also is seemingly random when the tearing happens, but the game doesn't usually stay smooth very long. Also I am experiencing micro-stutters, while I am getting a solid 60FPS the game feels much less smooth while gpu-screen-recorder is running

- [N/A] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [No] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
It's likely because you are using "focused" window capture method, try capturing the monitor instead. Also how many monitors do you have connected to the computer?

**Comment by Korgen1** [comment]
Yeah changing it to record a specific monitor seems to have fixed the issues, I was hoping I would be able to just record whatever window I had focused but this works, why does it cause those issues in that mode though?

**Comment by dec05eba** [comment]
I dont remember if its a gnome issue, if gnome enables the compositor when you capture a window or if its just how x11 works when you have vsync enabled in games. I generally dont enable vsync in games and dont use gnome so I dont remember.
