### ISSUE TITLE
[BUG] Mismatch for liba* libraries

### ISSUE THREAD

**Issue by ianfrossi0** [dec05eba/gpu-screen-recorder-issues#30]
**Describe the bug**
Similar as issue #28. Currently running on AUR version r631.42e5930-1. Multiple libraries required request a version which is not the latest provided one.

**To Reproduce**
1. Run `gpu-screen-recorder --help` or start a recording.
2. Receive error `gpu-screen-recorder: error while loading shared libraries: libavcodec.so.60: cannot open shared object file: No such file or directory`.

**Screenshots**
![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/71236104/0947d4a3-860b-464a-b7b2-9474f6b4f4ea)
![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/71236104/eefb4bad-3f3b-4086-82c9-a1aec401fcd4)

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: KDE Plasma 6.1
 - Distro: EndeavourOS
 - GPU: NVIDIA RTX 4080
 - Version (latest flatpak version, aur or source): AUR Latest

**Comment by dec05eba** [comment]
Did you reinstall gpu screen recorder as mentioned in my comment in #28 ?

**Comment by ianfrossi0** [comment]
Yes, just reinstalled once again to make sure the solution proposed in #28 worked, but unfortunately this did not solve the issue.

![image](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/71236104/995cb521-18a5-4e91-b064-b3b31c7dd6d4)

**Comment by dec05eba** [comment]
run `which gpu-screen-recorder` to make sure you dont have gpu screen recorder installed elsewhere. Also try first removing gpu screen recorder, clear your aur cache and install it again. I use arch with the aur package and I dont have this issue so the issue is somewhere in your install.

**Comment by dec05eba** [comment]
Oh wait EndeavourOS.. dont they use their own repositories? that might explain the issue. This issue doesn't appear on regular arch.

**Comment by ianfrossi0** [comment]
Issue is now fixed after rebuilding the AUR with `paru -S gpu-screen-recorder-git --rebuild`. I missed doing this beforehand.
