### ISSUE TITLE
[ENHANCEMENT REQUEST]

### ISSUE THREAD

**Issue by polluxau** [dec05eba/gpu-screen-recorder-issues#31]
**Describe the enhancement**
i'd highly recommend looking into amf encoding as amd added radv support for amf encode today

https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v1.4.34

**Comment by dec05eba** [comment]
This repository is ONLY for reporting issues. Also there is no reason to support amf in addition to vaapi, it's not better in any way to my knowledge.

**Comment by polluxau** [comment]
Oh ok my bad, you have a enhancement tag so thats why i created it

**Comment by dec05eba** [comment]
Oh I see. Those are the default ones. I removed them now.

**Comment by dec05eba** [comment]
Btw, the situation with amf vs vaapi was primarly an obs one, where obs used bad values for vaapi setup for years and that caused the quality to be worse than amf. It was fixed years later. Most people think that amf is better than vaapi because of that, but it's not really the case when you properly configure vaapi. A lot of information online is still from that time.

**Comment by polluxau** [comment]
> Btw, the situation with amf vs vaapi was primarly an obs one, where obs used bad values for vaapi setup for years and that caused the quality to be worse than amf. It was fixed years later. Most people think that amf is better than vaapi because of that, but it's not really the case when you properly configure vaapi. A lot of information online is still from that time.

True i agree :) love vaapi, isnt using quality=5 ffmpeg option all that is rlly needed for best quality under something like obs?

**Comment by dec05eba** [comment]
quality=5 is a h264 only option but yes it can improve quality a bit, but for some users it causes stutter in games so if amf uses that then that option cant be used by default anyways. hevc/av1 doesn't have that option and dont need it and you should use hevc/av1 anyways for best quality.
The issues obs had had to do with constant bitrate (CBR) parameters. Constant quality (CQP) on the other hand doesn't have the same issues.
