### ISSUE TITLE
[BUG] Recording flickering on latest Nvidia stable driver on Wayland

### ISSUE THREAD

**Issue by finnstacey** [dec05eba/gpu-screen-recorder-issues#34]
**Describe the bug**
When using either the Recording or Replay feature, the video flickers revealing the window behind the focused window. It only appears at the edges of the frame and only on Wayland. This issue is not present using X11.

**To Reproduce**
Using the Nvidia 555.58 driver on Wayland with the following settings:
Frame rate: 60
Video quality: High
Video codec: HEVC
Audio codec: Opus
Frame rate mode: Auto

**Screenshots**
What the broken frame looks like:
![Screenshot_20240707_121522](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/9073239/9dabaf85-0b22-4713-b1d1-cdcea2126e26)

Video of issue:
[https://youtu.be/D_x0gATdpgw](url)

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: KWin / KDE Plasma 6.1
 - Distro: Bazzite (Fedora immutable variant)
 - GPU: Nvidia RTX 3080 Ti
 - Version (latest flatpak version, aur or source): latest flatpak version (3.8.2)

**Additional context**
This issue did not occur on previous Nvidia driver. It also _does not_ happen using Nvenc HEVC in OBS Studio.

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
It's likely related to explicit sync in nvidia that was recently added to the nvidia driver and kde plasma. I dont know if it can be fixed until I add support for pipewire capture, but i'll take a look at it. Unfortunately I cant reproduce it myself so I'll just have to guess.

Also please dont exclude things from the issue template, include the output of drm_info as mentioned (by running `sudo drm_info > log.txt` and upload that file here. You need to install drm_info first).

**Comment by finnstacey** [comment]
Sorry for missing the drm_info output. It is attached.
[log.txt](https://github.com/user-attachments/files/16125792/log.txt)

As you guessed, this only appears in the video and not on my screen while I'm playing.

**Comment by finnstacey** [comment]
This has been fixed by updates to the Nvidia flatpak runtime.

**Comment by dec05eba** [comment]
Oh ok good to know. I was suspecting that it was an nvidia driver bug but I wasn't sure.
