### ISSUE TITLE
[BUG] No longer able to record after system update

### ISSUE THREAD

**Issue by Lassebq** [dec05eba/gpu-screen-recorder-issues#35]
**Describe the bug**
I have no idea what relevant package changed, but it seems that I'm no longer able to record anything using gpu-screen-recorder

**To Reproduce**
```
$ gpu-screen-recorder -w screen -f 60 -o video.mp4
Info: using h264 encoder because a codec was not specified
[h264_vaapi @ 0x59ee1ed07e40] ignoring invalid SAR: 0/0
[h264_vaapi @ 0x59ee1ed07e40] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
Error: no available output found
```
**Screenshots**
GTK GUI Without DRI_PRIME=1:
![image](https://github.com/user-attachments/assets/3257daa4-5e4e-408c-879f-5d50f287a423)

GTK GUI With DRI_PRIME=1:
![image](https://github.com/user-attachments/assets/0cee6387-3b70-4dd2-99af-f86603895c74)

**Desktop (please complete the following information):**
 - X11 or Wayland: X11 and Wayland
- Desktop environment/Window Manager: GNOME
 - Distro: Arch
 - GPU: Radeon RX 580
 - Version (latest flatpak version, aur or source): aur

**Additional context**
OBS still seems to recognize both cards and can capture videos from them.

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU
- [x] I use a desktop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
Please dont remove things from the issue template.. Run `sudo drm_info > log.txt` and upload that log file here.

**Comment by Lassebq** [comment]
[log.txt](https://github.com/user-attachments/files/16237603/log.txt)

**Comment by Lassebq** [comment]
Look like it's related to using `amdgpu.dc=0` kernel parameter.
Display Core is such a pain in the ass due to https://gitlab.freedesktop.org/drm/amd/-/issues/662
