### ISSUE TITLE
[BUG] Using HEVC codec outputs 1920x1088 video file from 1920x1080 record area

### ISSUE THREAD

**Issue by Lassebq** [dec05eba/gpu-screen-recorder-issues#36]
**Describe the bug**
When choosing HEVC encoder in gpu-screen-recorder-gtk the output video file contains extra 4 pixels of black bars on top and bottom

**To Reproduce**
Monitor HDMI-A-1 (1920x1080)
Framerate: 30
Video codec: HEVC
Audio codec: Opus
Framerate mode: VFR

**Screenshots**
![image](https://github.com/user-attachments/assets/b7413f71-0bdf-4d1e-b526-3a07897cce50)

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: GNOME
 - Distro: Arch
 - GPU: Radeon RX 580
 - Version (latest flatpak version, aur or source): aur

**Additional context**
`sudo drm_info > log.txt`
[log.txt](https://github.com/user-attachments/files/16262870/log.txt)
Attach a video that shows the issue:
https://github.com/user-attachments/assets/6e8eb129-0be4-46ed-b117-0f603280185c

Happens when recording both window and desktop
Does not seem to happen when recording HEVC using vaapi from OBS Studio.

- [x] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
It's an amd driver bug when using hardware video encoding. av1 has the same issue but that one is an amd hardware bug that can never be fixed.

**Comment by Lassebq** [comment]
According to the linked issue it's already fixed in mesa. But supposedly requires a change in ffmpeg.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/10985
I assume this project does not depend on ffmpeg so it's up to you to fix?

**Comment by Lassebq** [comment]
Oh, nevermind. It does. I guess I'll be waiting for fix in ffmpeg.

**Comment by dec05eba** [comment]
Im not actually really sure if that fixes the issue, but we will have to see

**Comment by Lassebq** [comment]
@dec05eba Re-encoding a 1920x1080 video with ffmpeg and -c:v hevc_vaapi does not produce extra 8 pixels.
```ffmpeg -vaapi_device /dev/dri/renderD128 -i input.mp4 -vf 'format=nv12,hwupload' -c:v hevc_vaapi output.mp4```
Also doesn't happen with OBS
gpu-screen-recorder adds extra 8 pixels regardless
This happens with and without [patch](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240321170219.1487-1-Primeadvice@gmail.com/) applied.

**Comment by Lassebq** [comment]
Also tried exact same command from this issue https://gitlab.freedesktop.org/mesa/mesa/-/issues/10985
Outputs a 1920x1080 video

**Comment by dec05eba** [comment]
@Lassebq  it stills outputs a 1920x1088 video for me (on arch linux)

**Comment by Lassebq** [comment]
vainfo on Arch:
```
vainfo: VA-API version: 1.21 (libva 2.22.0)
vainfo: Driver version: Mesa Gallium driver 24.1.3-arch1.1 for AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.57, 6.9.9-arch1-1)
```

/dev/dri/renderD128 is amdgpu on alpine
/dev/dri/renderD129 is amdgpu on arch
Re-encoding via vaapi on both distros gets rid of the black bars
Source video (re-encoded via libx265 to fit under upload limit):

https://github.com/user-attachments/assets/b3ba573a-4de8-463e-821e-91f2cd459766

Output video (on arch) from
```
ffmpeg -vaapi_device /dev/dri/renderD129 -hwaccel vaapi -hwaccel_output_format vaapi -i HEVC.mp4 -t 0:00:10 -filter:v "hwdownload,crop=1920:1080:0:4,format=nv12,hwupload" \
 -vcodec hevc_vaapi -rc_mode CQP -qp 32 a.mp4
 ```

https://github.com/user-attachments/assets/c18b48ff-82d4-4bad-9e21-834cf2724c2f

**Comment by dec05eba** [comment]
i tested with that video and exact same command and the video is 1088p for me on 7800xt, va-api version 1.22, mesa version 24.1.5, ffmpeg version n7.0.1.
Which ffmpeg version are you using?

**Comment by Lassebq** [comment]
I'm free to test any patches that could fix it in gpu-screen-recorder. So please let me know.
I'm unable to test OBS on arch because for some reason pipewire capture source is missing. But I'm pretty sure it was outputting 1920x1080 HEVC when it still worked
ffmpeg:
```
ffmpeg version n7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
```

**Comment by Lassebq** [comment]
Currently updating mesa, going to test again.

**Comment by dec05eba** [comment]
mesa has different code for different video encoding engines, so it could be broken for 7800xt but not rx 580.. :(

**Comment by Lassebq** [comment]
After update still getting 1920x1080, no extra pixels. I'm just really confused as to why gpu-screen-recorder output has this side effect

**Comment by dec05eba** [comment]
gpu screen recorder adds padding itself to match the padding added by mesa to avoid glitched graphics in the padding area

**Comment by Lassebq** [comment]
Alright, going to test without these 2 lines

**Comment by Lassebq** [comment]
Yep, no issues on my end after getting rid of FFALIGN

**Comment by dec05eba** [comment]
I guess the issue will have to get reported to mesa again

**Comment by Lassebq** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/10985
Assuming that's the same issue, the reporter had 6650 XT, which I'm assuming is VCE 4?
Weird that it got solved for them but not for your exact GPU

**Comment by dec05eba** [comment]
the reporter never said that it was fixed for them in that issue report, so im not sure if it actually was fixed for 6650 xt

**Comment by Lassebq** [comment]
Oh, true :(

**Comment by dec05eba** [comment]
Which version of VNC firmware do you have? that info should be available if you run `sudo dmesg | grep "VCN firmware`

**Comment by Lassebq** [comment]
[    0.286909] [drm] Found UVD firmware Version: 1.130 Family ID: 16
[    0.288110] [drm] Found VCE firmware Version: 53.26 Binary ID: 3
No VCN in dmesg

**Comment by dec05eba** [comment]
I commented on the issue report on mesa. Hopefully I will get a response.

**Comment by dec05eba** [comment]
You said that its fixed with and without this patch https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240321170219.1487-1-Primeadvice@gmail.com/ right? but are you sure you removed the patch after you tested it? It works on 7800xt if I apply that patch.

**Comment by Lassebq** [comment]
Yes, I replaced ffmpeg with repo version which doesn't apply this patch

**Comment by Lassebq** [comment]
And I can re-encode 1920x1080 hevc on arch, where I didn't do any patching

**Comment by Lassebq** [comment]
I think there's a critical bit of info that I forgot to mention:
```
[hevc_vaapi @ 0x58520bba98c0] ignoring invalid SAR: 0/0
[hevc_vaapi @ 0x58520bba98c0] Driver does not advertise encoder features, using guessed defaults.
[hevc_vaapi @ 0x58520bba98c0] Driver does not advertise encoder block size, using guessed defaults.
[hevc_vaapi @ 0x58520bba98c0] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
```
With h264 I only get:
```
[h264_vaapi @ 0x5e777740c440] ignoring invalid SAR: 0/0
[h264_vaapi @ 0x5e777740c440] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
```
