### ISSUE TITLE
[BUG] Direct screen capture is failing on AMD Wayland

### ISSUE THREAD

**Issue by TTtie** [dec05eba/gpu-screen-recorder-issues#38]
**Describe the bug**
Using direct screen capture with `gpu-screen-recorder` results in a failure to get the KMS plane and no video being output in the resulting file. (On an unrelated note, the GUI hangs if stopping a recording that fails like this.)

Using the PipeWire desktop portal works just fine, including the GUI. 

**To Reproduce**
```bash
# command line equivalent of my GUI options
gpu-screen-recorder -w DP-2 -c matroska -q very_high -k av1 -ac opus -f 165 -cursor yes -cr full -encoder gpu -o test.mkv -a "$(pactl get-default-sink).monitor" -a "$(pactl get-default-source)"

# minimal repro
gpu-screen-recorder -w DP-2 -o test.mp4 -f 60
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: Plasma 6.1.3
 - Distro: Fedora 40
 - GPU: AMD Radeon RX 7700 XT
 - Version (latest flatpak version, aur or source): source: `7e07ad1b6ef467df4b6da12c65094a7ebc0b48ed` 
   - the last commit where direct capture works for me is `b077177081c61bce1b1e5247389a09383369a827`, if it helps

**Additional context**
DRM info: [drm_info.txt](https://github.com/user-attachments/files/16351012/drm_info.txt)

Console output:
```console
$ gpu-screen-recorder -w DP-2 -c matroska -q very_high -k av1 -ac opus -f 165 -cursor yes -cr full -encoder gpu -o test.mkv -a "$(pactl get-default-sink).monitor" -a "$(pactl get-default-source)"
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
[av1_vaapi @ 0x22f1e00] ignoring invalid SAR: 0/0
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[av1_vaapi @ 0x22f1e00] ignoring invalid SAR: 0/0
gsr error: gsr_kms_client_get_kms: failed to receive response
gsr error: gsr_capture_kms_capture: failed to get kms, error: 4 (failed to receive)
# # the above 2 lines are spammed for the length of the recording
```

- [x] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
I just noticed that myself, it should be fixed now
