### ISSUE TITLE
[BUG] Recording breaks when monitors are shut off with DPMS

### ISSUE THREAD

**Issue by alexwh** [dec05eba/gpu-screen-recorder-issues#4]
**Describe the bug**
When the monitors are shut off via DPMS, either through something like `xset dpms force off` or KDE's "Turn off screen" setting in Energy Saving settings, the recording will continue with audio, but the video will  be stuck on the last frame displayed. In addition, the log `gsr error: gsr_capture_nvfbc_capture failed: A capture to a GL buffer session has not been created for this NvFBC client` is spammed multiple times per second on stderr.

**To Reproduce**
`gpu-screen-recorder -v no -w DP-0 -c mp4 -q very_high -k auto -ac opus -a alsa_output.usb-Schiit_Audio_Schiit_Unison_Universal_Dac-00.analog-stereo.monitor -f 60 -r 600 -o /home/alex/Videos/shadowplay -mf yes -a alsa_input.usb-Elgato_Systems_Elgato_Wave_1_AS47J1A01425-00.mono-fallback -cr limited`
then
`xset dpms force off`

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: KDE Plasma 6.0.3
 - Distro: Arch Linux
 - GPU: NVIDIA GTX 1060
 - Version: AUR gpu-screen-recorder-git r539.9bc8cbb-1

**Additional context**
[gsr.log](https://github.com/dec05eba/gpu-screen-recorder-issues/files/14895322/gsr.log)
[drm_info.log](https://github.com/dec05eba/gpu-screen-recorder-issues/files/14895327/drm_info.log)
OBS screen recording:
https://github.com/dec05eba/gpu-screen-recorder-issues/assets/1723612/1ea18ae7-c433-4449-bd53-1cb429bb6397
Raw output:
https://github.com/dec05eba/gpu-screen-recorder-issues/assets/1723612/7ee5f9ab-9af2-4a32-bec3-55c317ff29ba

- [x] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
Have you followed this part of the README (https://git.dec05eba.com/gpu-screen-recorder/about/): 
```
Nvidia drivers have an issue where CUDA breaks if CUDA is running when suspend/hibernation happens, and it remains broken until you reload the nvidia driver. To fix this, either disable suspend or tell the NVIDIA driver to preserve video memory on suspend/hibernate by using the NVreg_PreserveVideoMemoryAllocations=1 option. You can run sudo extra/install_preserve_video_memory.sh to automatically add that option to your system.
```
?

**Comment by alexwh** [comment]
I added `options nvidia NVreg_PreserveVideoMemoryAllocations=1` to `/etc/modprobe.d/gsr-nvidia.conf` but the issue still persists. It doesn't seem to have applied after a reboot in `/sys/module/nvidia/parameters` (dir doesn't exist), though.

**Comment by dec05eba** [comment]
Ok i'll try and see if I also get this issue when I have time to setup my nvidia gpu

**Comment by dec05eba** [comment]
I fixed it now (and also capture breaking after monitor reconfiguration). The fix is on git and will soon be in aur (version r544.d5bf41f)

**Comment by alexwh** [comment]
Awesome! Thank you for the very fast turnaround!
