### ISSUE TITLE
[BUG] GTK fails to record if audio source has a space

### ISSUE THREAD

**Issue by SeongGino** [dec05eba/gpu-screen-recorder-issues#44]
**Describe the bug**
When using GPU Screen Recorder GTK, attempting to record fails if a recorded audio source contains a space in its path name - e.g. `Virtual Audio Source.monitor`.

**To Reproduce**
Using the GUI, on top of `default_output`, I added two sources; `Virtual Audio Source 1.monitor` and `Virtual Audio Source 2.monitor`. 

**Screenshots**
![2024_08-17 133116-GPU Screen Recorder | Running on NVIDIA](https://github.com/user-attachments/assets/b60fee9d-8809-4082-98e4-bc16df54b594)

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: KDE Plasma 6.1.4
 - Distro: Arch Linux
 - GPU: NVIDIA GeForce RTX 3060ti
 - Version (latest flatpak version, aur or source): `gpu-screen-recorder(-gtk)` from AUR.

**Additional context**
Terminal output:
```
Error: Audio input device 'Virtual' is not a valid audio device, expected one of:
    default_output (Default output)
    default_input (Default input)
    Virtual Audio Source 2.monitor (Monitor of Virtual Audio Source 2)
    Virtual Audio Source 3.monitor (Monitor of Virtual Audio Source 3)
    Virtual Audio Source 1.monitor (Monitor of Virtual Audio Source 1)
    rnnoise_source (Noise Canceling Mic)
    alsa_output.pci-0000_07_00.1.hdmi-stereo.monitor (Monitor of GA104 High Definition Audio Controller Digital Stereo (HDMI))
    alsa_input.usb-audio-technica_AT2020USB_-00.analog-stereo (AT2020USB+ Analog Stereo)
    alsa_output.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FiiO_K3-00.analog-stereo.monitor (Monitor of FiiO K3 Analog Stereo)
```

**Comment by dec05eba** [comment]
ah damn, virtual audio sources.. I'll fix it in a moment

**Comment by dec05eba** [comment]
It should be fixed now. Can you update gpu-screen-recorder-git and gpu-screen-recorder-gtk-git from aur and verify that it works now? and check if the video looks fine, I changed some other things as well

**Comment by dec05eba** [comment]
It should be fixed now. Can you update gpu-screen-recorder-git and gpu-screen-recorder-gtk-git from aur and verify that it works now? and check if the video looks fine, I changed some other things as well

**Comment by SeongGino** [comment]
Seems to work fine now, as does the video appears fine too.
