### ISSUE TITLE
[BUG] Can neither record nor replay

### ISSUE THREAD

**Issue by tsuza** [dec05eba/gpu-screen-recorder-issues#45]
**Describe the bug**
Whenever I try to record / start replay, the recording / replay instantly stops and I get the following message:

> GPU Screen Recorder, body: Failed to start replay. Either your graphics card doesn't support GPU Screen Recorder with the settings you used or you don't have enough disk space to record a video

If I try to start it from the CLI, I get the following output ( from booting it up to trying to record ):
```
Warning: failed to connect to the X server. Assuming wayland is running without Xwayland
gsr error: failed to initialize global shortcuts
pkexec version 124
/home/suza
Warning: failed to connect to the X server. Assuming wayland is running without Xwayland
[h264_nvenc @ 0x5579a8d57680] ignoring invalid SAR: 0/0
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[h264_nvenc @ 0x5579a8d57680] ignoring invalid SAR: 0/0
Notification: title: GPU Screen Recorder, body: Failed to start replay. Either your graphics card doesn't support GPU Screen Recorder with the settings you used or you don't have enough disk space to record a video
Warning: failed to connect to the X server. Assuming wayland is running without Xwayland
```

**To Reproduce**
It happens with any option, both GUI and CLI.

1.  Install GPU Screen Recorder through Flatpak.
2. Install GPU Screen Recorder System Wide, otherwise it refuses to record / replay altogether.
3. Record / replay.

**Screenshots**

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: Gnome
 - Distro: Nobara 40
 - GPU: RTX 4060ti
 - Version (latest flatpak version, aur or source): Flatpak ver. 4.1.2

**Additional context**
I'm not setting any env var. I've tried to give some additional permissions to GPU Screen Recorder through flatseal, but it did not help.
Recording works on OBS, if this piece of info helps.

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

[log.txt](https://github.com/user-attachments/files/16648943/log.txt)

**Comment by tsuza** [comment]
**Update:** If I select "Desktop portal (Experimental, HDR not supported)", it stops complaining and starts recording. Are there any drawbacks than choosing a specific monitor ( apart from HDR not being supported, which is a non-issue for me )? Or is it specifically due to Wayland, thus it needs to be used?

**Comment by dec05eba** [comment]
> **Update:** If I select "Desktop portal (Experimental, HDR not supported)", it stops complaining and starts recording. Are there any drawbacks than choosing a specific monitor ( apart from HDR not being supported, which is a non-issue for me )? Or is it specifically due to Wayland, thus it needs to be used?

on a correctly setup wayland system there isn't really any difference aside from hdr as you stated, and yes it's only available on wayland.

As for this issue, can you run `flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 60 -o video.mp4` and post the terminal output here?
if it crashes (stops by itself without recording anything) then can you run `coredumpctl gdb`) and copy the terminal output of that here?

**Comment by dec05eba** [comment]
Oh no need to run that, I see the issue now.

**Comment by tsuza** [comment]
Aha, gotcha. Is there anything you can do about it ( e.g. forcefully installing x11 for the app )? Thankfully it works with Desktop portal, and I'm on a Desktop, so it's not a big issue for now.

**Comment by dec05eba** [comment]
I have fixed the issue now. The fix will be available in the flatpak soon: https://github.com/flathub/com.dec05eba.gpu_screen_recorder/pull/143
Thanks for reporting the issue so I could catch it early!

**Comment by tsuza** [comment]
Thank you for being so quick!

**Comment by tsuza** [comment]
Just an update for you, I've just installed the latest flatpak version and now it works perfectly. Thanks once again!
