### ISSUE TITLE
[BUG] bitrate increases significantly while recording

### ISSUE THREAD

**Issue by jojommeke** [dec05eba/gpu-screen-recorder-issues#46]
**Describe the bug**

Bitrate increased significantly over time making the files very big

**To Reproduce**
The GPU Screen Recorder command you ran or if you used the GUI version then describe which options you used.

Take your steam deck on desktop mode, install the app via discover, record screen on medium quality mkv, other default settings

Record 10s -> low bitrate(check in dolphin)

Record 10 min -> wayy higher bitrate

Record more -> overkill bitrate

**Screenshots**

**Desktop (please complete the following information):**
 - **X11** or ~~Wayland~~
- Desktop environment/Window Manager: kde / x11
 - Distro: arch/steamos
 - GPU: steam deck apu
 - Version (latest flatpak version, aur or source):

Latest flatpak via discover

**Additional context**
Add any other context about the problem here, such as terminal output of running GPU Screen Recorder and if the issue isn't related to audio then please run `sudo drm_info > log.txt` and attach that log.txt file in this bug report. drm_info can be installed from your package manager or from https://gitlab.freedesktop.org/emersion/drm_info.
Attach a video that shows the issue (if applicable), in raw form as output by GPU Screen Recorder or a losslessly cut version of it (you can use https://flathub.org/apps/org.gnome.gitlab.YaLTeR.VideoTrimmer for example to do this).
Which game did you run while recording (if any) and does the issue also happen if you only record your desktop?
Does the issue also happen if you use obs studio instead with equivalent settings (video encoding settings and audio codec settings. Nvenc on nvidia and vaapi on amd/intel and same video/audio codec)?
If you have an issue with audio make sure you are not using pulseaudio/pipewire audio processing software such as EasyEffects.
If you are setting any amd/intel/nvidia/mesa/vaapi/pulseaudio/pipewire environment variables then please list those.

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable) -> will try
- [ ] ~~I use a laptop with an integrated GPU and a dedicated GPU~~

**Comment by dec05eba** [comment]
This is a bug in the steam decks gpu driver, I have reported it here: https://github.com/ValveSoftware/SteamOS/issues/1609
Thats why gpu screen recorder has been disabled on steam deck now with the latest version

**Comment by jojommeke** [comment]
Any fix?

**Comment by dec05eba** [comment]
There is a workaround but I wont do it anytime soon. Valve will have to fix it instead. They dont have a proper place to report steam deck bugs so I dont even know where to report it. They dont have a public space to report steam deck software issues (even their fork of mesa, etc, are hidden).

**Comment by jojommeke** [comment]
> This is a bug in the steam decks gpu driver, I have reported it here: https://github.com/ValveSoftware/SteamOS/issues/1609
> Thats why gpu screen recorder has been disabled on steam deck now with the latest version

So this is also the case with OBS and others?

**Comment by dec05eba** [comment]
yes, if you choose qp quality option. But steam deck also has an issue with the capture method itself. The driver has many small bugs like that.

**Comment by jojommeke** [comment]
> There is a workaround but I wont do it anytime soon as there are also other steam deck bugs. Valve will have to fix it instead. They dont have a proper place to report steam deck bugs so I dont even know where to report it. They dont have a public space to report steam deck software issues (even their fork of mesa, etc, are hidden).

Can you explain the workaround maybe I can help

**Comment by dec05eba** [comment]
its to use constant bitrate/variable bitrate instead of constant quality. But that doesn't fix it fully as the capture method also has glitches. Its another bug that I haven't reported yet.

**Comment by jojommeke** [comment]
> its to use constant bitrate/variable bitrate instead of constant quality. But that doesn't fix it fully as the capture method also has glitches. Its another bug that I haven't reported yet.

So constant bitrate fixes Filesize etc but the recording starts glitching?

**Comment by dec05eba** [comment]
the glitching happens right now even without any changes, so its unrelated to that. But yes constant bitrate fixes file size.

**Comment by jojommeke** [comment]
> the glitching happens right now even without any changes, so its unrelated to that. But yes constant bitrate fixes file size.
> You can see the glitching if you move a window around for example.

Im not experiencing those glitches so that's fine for me, can I enable constant bitrate on gpu screen recorder?

**Comment by dec05eba** [comment]
There is no option for that, code needs to be written for that and it needs to take into consideration each different codec, hdr, resolution, gpu vendor, etc.

**Comment by jojommeke** [comment]
> There is no option for that, code needs to be written for that and it needs to take into consideration each different codec and quality option, hdr, resolution, gpu vendor, etc.

Maybe like a steam deck preset that uses CBR and the best settings/settings that work on deck would be nice

**Comment by dec05eba** [comment]
Maybe but the other issue remains. I dont want to enable something that only works randomly and with luck. Once that issue has been solved then I can do a steam deck specific solution.
Right now if people want to record on steam deck they can use the steam built-in recorder in the steam beta. That one is also hardware accelerated.

**Comment by jojommeke** [comment]
> Maybe but the other issue remains. I dont want to enable something that only works randomly and with luck. Once that issue has been solved then I can do a steam deck specific solution.
> Right now if people want to record on steam deck they can use the steam built-in recorder in the steam beta. That one is also hardware accelerated.

I looked through the code a bit and there seems to be much commented code related to CBR, can you explain?, maybe I can try something myself

**Comment by jojommeke** [comment]
Maybe make it so there is a link to your issue when the steam deck is detected so they can say they are impacted by the bug to boost the issue, also maybe try steamos beta see if it's fixed

**Comment by dec05eba** [comment]
I worked around the issue by using VBR on steam deck and added a warning the first time you start gpu screen recorder that says that steam deck has buggy drivers and a link to that issue.
The fix will be available in flathub in a few hours when flathub updates it.

**Comment by jojommeke** [comment]
> I worked around the issue by using VBR on steam deck and added a warning the first time you start gpu screen recorder that says that steam deck has buggy drivers and a link to that issue.
> The fix will be available in flathub in a few hours when flathub updates it.

So you will be releasing a fix? Tysm it means a lot to me really

**Comment by dec05eba** [comment]
> So you will be releasing a fix? Tysm it means a lot to me really

it has already been released

**Comment by jojommeke** [comment]
I just wanna say you are really the best, it works flawlessly and the new features are awesome!
