### ISSUE TITLE
[BUG] When recording in HDR GSR also records Nigh Light

### ISSUE THREAD

**Issue by OlegAckbar** [dec05eba/gpu-screen-recorder-issues#47]
**Describe the bug**
When recording in HDR GSR also records Nigh Light which is unwanted and makes videos orange.

**To Reproduce**
Try recording anything with HDR and Night Light enabled on KDE

**Screenshots**
I think it's better to watch this webm in mpv on desktop since it's encoded in HDR.

[Replay_2024-09-16_20-56-05.webm](https://github.com/user-attachments/assets/d37f97a6-4a02-4dd6-b90b-018f1c13972d)

**Desktop (please complete the following information):**
 - Wayland
- Desktop environment/Window Manager: KDE
 - Distro: Arch Linux
 - GPU: RX 6700 XT
 - Version (latest flatpak version, aur or source): aur r770.7145619-1

**Additional context**
[drm_info.txt](https://github.com/user-attachments/files/17019035/drm_info.txt)

**Comment by OlegAckbar** [comment]
Here's another example. As you can see, Spectacle records screen just fine.

[Запись экрана_20240916_224716.webm](https://github.com/user-attachments/assets/e8d8ac60-ac96-421c-ab7c-8b2a3d9677eb)

**Comment by dec05eba** [comment]
It's not possible to remove the night light when recording monitor with hdr as it displays exactly what you are recording. Try recording with desktop portal option instead (-w portal if you are using gsr command line). I believe thats what spectacle is using so it should work the same way. This option doesn't support hdr so the video will have hdr tonemapped to sdr instead, just like spectacle (unless im incorrect and spectacle supports hdr).

**Comment by dec05eba** [comment]
Or actually, it might be possible to ignore it. Let me look into it.

**Comment by dec05eba** [comment]
Ok it cant really be fixed. The night light color is mixed with the hdr data. You have to record with desktop portal option instead. I tested that and it works like spectacle. Select desktop portal (-w portal) and h264/hevc/av1 as codec.
