### ISSUE TITLE
[BUG] Broken audio when merging two audio tracks.

### ISSUE THREAD

**Issue by arttuc** [dec05eba/gpu-screen-recorder-issues#48]
**Describe the bug**
Recording with two audio tracks merged results in buzzing or no sound.
Works fine with just one audio track.

**To Reproduce**
`gpu-screen-recorder -w "DP-1" -f 15 -a "default_output|default_input" -q medium -o "$HOME/Työpöytä/output.mp4"`
`mpv --no-config output.mp4`

**Screenshots**
Video with buzzing on the start and then no sound after.
https://github.com/user-attachments/assets/138035f3-4807-4ff9-919e-11d150487063

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: KDE Plasma 6.1.1 with KWin
 - Distro: Arch Linux
 - GPU: AMD Radeon RX 6700 XT
 - Version (latest flatpak version, aur or source): AUR r770.7145619-1

**Additional context**
Example video shows Factorio but the content doesn't matter.

```
$ gpu-screen-recorder -w "DP-1" -f 15 -a "default_output|default_input" -q medium -o "$HOME/Työpöytä/output.mp4"
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
Info: using h264 encoder because a codec was not specified
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[h264_vaapi @ 0x604676fca400] ignoring invalid SAR: 0/0
[h264_vaapi @ 0x604676fca400] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
update fps: 16, damage fps: 16
update fps: 15, damage fps: 15
update fps: 15, damage fps: 15
update fps: 15, damage fps: 15
update fps: 15, damage fps: 15
update fps: 15, damage fps: 15
^C
```
```
$ mpv --no-config output.mp4
 (+) Video --vid=1 (*) (h264 2560x1440 14.985fps)
 (+) Audio --aid=1 (*) (opus 2ch 48000Hz)
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [gpu] 2560x1440 yuv420p
AV: 00:00:06 / 00:00:06 (99%) A-V:  0.000
Exiting... (End of file)
```

- [x] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
Thanks, I can reproduce it, it's a regression in a very recent change. I have fixed it and will push the fix soon.

**Comment by dec05eba** [comment]
It should be fixed now. The update is in aur now as well (version r782.85d35be). Thanks!
