### ISSUE TITLE
[BUG] Audio recording is noticeably quieter compared to audio source

### ISSUE THREAD

**Issue by fiftydinar** [dec05eba/gpu-screen-recorder-issues#5]
**Describe the bug**
When recording the audio from the "Default output" source, to record desktop audio, I notice that sound is quieter than it should be.

**To Reproduce**
Just run the recording & you will notice it.

**Expected behavior**
Audio should match the volume levels that are played in audio source (desktop).

**Desktop**
- Wayland
- Gnome
- Fedora Silverblue 39 (Universal Blue version)
- AMD RX 6600
- Flatpak v3.6.4

**Additional context**
Audio codec doesn't matter here, as it doesn't change anything.

This might be a PipeWire bug, not the bug of this application, but I'm not sure, so that's why I'm reporting here.

**Comment by dec05eba** [comment]
It's important that you keep things from the reporting template. Have you played the video with the command from the reporting template ? (`mpv --no-config video.mp4`) start a recording, open pavucontrol and check the recording tab and make sure its at 100% volume. If it's at 100% volume, recording with gpu screen recorder and obs studio at the same time, from the same default output source while playing music and upload the video clips here (or any other site).

**Comment by fiftydinar** [comment]
> Have you played the video with the command from the reporting template ? (`mpv --no-config video.mp4`) start a recording, open pavucontrol and check the recording tab and make sure its at 100% volume. If it's at 100% volume, record with gpu screen recorder and obs studio at the same time, from the same default output source while playing music and upload the video clips here (or any other site).

I don't use mpv nor pavucontrol, so this will take some time.

Mic is at 100% volume in Gnome quick settings.

Perhaps Pipewire 100% volume is not the same as PulseAudio (pavucontrol) 100% volume?

**Comment by dec05eba** [comment]
mic and recording tab is not the same

**Comment by fiftydinar** [comment]
> It's important that you keep things from the reporting template. Have you played the video with the command from the reporting template ? (`mpv --no-config video.mp4`)

Just played it now, no changes in volume.

> Start a recording, open pavucontrol and check the recording tab and make sure its at 100% volume.

Verified.

> If it's at 100% volume, record with gpu screen recorder and obs studio at the same time, from the same default output source while playing music and upload the video clips here (or any other site).

I used flatpak version of OBS.

GPU Screen Recorder: https://archive.org/download/gpu-screen-recorder-2024-04-07-13-02-58/GPU-Screen-Recorder_2024-04-07_13-02-58.mp4
OBS: https://archive.org/download/gpu-screen-recorder-2024-04-07-13-02-58/OBS-2024-04-07%2013-02-57.mkv

Both have the same issue.

When I set the volume in Recording in pavucontrol around 145-150% (+10-10.5db), I get the volume level that it should be for 100% volume in the 1st place.

**Comment by dec05eba** [comment]
If both gpu screen recorder and obs has the same issue then it's not an issue in gpu screen recorder or something gpu screen recorder can likely fix, so i'll close this

**Comment by dec05eba** [comment]
But check playback volume and output device volume in pavucontrol, you might have it above 100%. Note that applications record the at 100% volume even if your output device has volume set to 150% or something like that.

**Comment by fiftydinar** [comment]
> But check playback volume and output device volume in pavucontrol, you might have it above 100%. Note that applications record at 100% volume even if your output device/system volume has volume set to 50% or 150%.

Playback & output device volume is not above 100%.
But thanks for feedback & help in troubleshooting, I will report this somewhere in Pipewire GitLab.

**Comment by fiftydinar** [comment]
It turns out that the issue was mine, with EasyEffects applying it's processing to the GPU Screen Recorder audio recording, including the -9db gain that I set for the EQ effect.

When I set the gain to 0db or disable EasyEffects completely, issue goes away.

My apologies for taking your time on investigating this issue.
