### ISSUE TITLE
[BUG] Screen width wider than 4096 are unsupported

### ISSUE THREAD

**Issue by PossumGS** [dec05eba/gpu-screen-recorder-issues#53]
**Describe the bug**
My monitor resolution is 5120x1440. If I try to start a recording on that monitor I see:
- ignoring invalid SAR: 0/0
- Width 5120 exceeds 4096
- Provided device doesn't support required NVENC features

I have a two monitor setup. If I try to record my 1920x1080 monitor, everything works correctly.

**To Reproduce**
Run gpu-screen-recorder-gtk
Attempt to start a recording on a monitor that exceeds the 4096 resolution limit. 

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: KDE Plasma 6.2.0
 - Distro: Arch
 - GPU: RTX 3080 
 - Version (latest flatpak version, aur or source): aur gtk version

**Comment by dec05eba** [comment]
It's not a bug, your gpu doesn't support that resolution. Try changing video codec to hevc instead, it might support higher resolution.

**Comment by PossumGS** [comment]
> It's not a bug, your gpu doesn't support that resolution for video encoding (for h264). Try changing video codec to hevc instead, it might support higher resolution. I will consider automatically defaulting to hevc when recording at higher resolution than 4096.

Thank you. HEVC does indeed support higher resolutions.
