### ISSUE TITLE
[BUG] two separate audio tracks on video.

### ISSUE THREAD

**Issue by mikosenigma** [dec05eba/gpu-screen-recorder-issues#54]
I have 3 questions. I don't know where I could ask them

1. it is impossible to save a video with two tracks (audio from the game and audio from the microphone on two separate tracks) or I can't set something properly? Only the audio captured from the game is always recorded.

2. is it possible to set the volume level for audio output and input? E.g. Mute the game sounds and turn up the microphone? Can this be set in some configuration files? Is it planned to create such a function in the GUI?

3. is it planned to support webcam capture as a second video source? I'll admit that GPU Screen recorder is definitely cooler than OBS, and I think I'm not the only one waiting for such features. I would be happy to financially support the project.

Wayland
Nobara OS 40
Gnome (Standard)
Radeon RX 6600 XT
Flatpak verion.

**Comment by dec05eba** [comment]
1. Just add two audio tracks and untick the "merge audio tracks" option
2. no and its not planned at the moment. you have to do that through your system audio controls and/or wireplumber
3. webcam support is planned yes, but its a lower priority feature

**Comment by mikosenigma** [comment]
> 1. Just add two audio tracks. One of the desktop audio (default output) and one of the microphone (default input) and untick the "merge audio tracks" option

Thank you for your quick response. Every time I uncheck the “merge audio tracks” option I only get one track in the end. No audio from mic. It is possible that it will appear only in some video editor. E.g. Kadenlive. I have to check it. Sorry for writing here. I couldn't find any chat or link.

**Comment by dec05eba** [comment]
The link ins the README is to my website where you find my contact email. Anyways, maybe that is the case. Try opening the video with mpv. You will be able to see 2 audio tracks that you can switch between:
![Screenshot_2024-10-14_14-16-45](https://github.com/user-attachments/assets/70c1aa24-7fa9-4c20-b3c2-1e401f101212)

**Comment by dec05eba** [comment]
![Screenshot_2024-10-14_17-26-10](https://github.com/user-attachments/assets/40274945-bb5e-4755-ace2-ce993aff698c)
This is also what it should look like in the gpu screen recorder ui to add two audio tracks that are separate audio tracks in the video file. You can try saving the file in mkv format instead if your video player / editor doesn't support mp4 files with multiple audio tracks.
