### ISSUE TITLE
[BUG] Invalid file '/run/current-system/sw/bin/gsr-kms-server' for capability operation

### ISSUE THREAD

**Issue by Gxnum** [dec05eba/gpu-screen-recorder-issues#55]
Running `gpu-screen-recorder -w screen -f 60 -c mp4 -a alsa_output.pci-0000_00_1f.3.analog-stereo.monitor -r 60 -o ~/Videos/` requires authentication for org.freedesktop.policykit.exec. According to the program, in order to bypass that, I must run `sudo setcap cap_sys_admin+ep '/run/current-system/sw/bin/gsr-kms-server'`. However, that returns with an error of `Invalid file '/run/current-system/sw/bin/gsr-kms-server' for capability operation`.

Device: Dell Vostro
CPU: Intel i3 12100
GPU: Nvidia GTX 1650
Distro: NixOS Unstable
Screen: Wayland
Version: latest from NixOS package store

**Comment by dec05eba** [comment]
The issue has been reported in nixos before: https://github.com/NixOS/nixpkgs/issues/349648 and the fix is here: https://github.com/NixOS/nixpkgs/pull/349665

**Comment by Gxnum** [comment]
Oh my bad. Thanks!

**Comment by dec05eba** [comment]
After that has been merged and it's not fixed yet then you can re-open this (or if you are willing to try that pull request)
