### ISSUE TITLE
[BUG] Audio device names containing a `/` prevent recording in the GUI

### ISSUE THREAD

**Issue by FreezyLemon** [dec05eba/gpu-screen-recorder-issues#56]
**Describe the bug**
I have an audio device that contains a forward slash `/` in its name:
```sh
$ gpu-screen-recorder --list-audio-devices
default_output|Default output
default_input|Default input
...
NoiseTorch Microphone for Starship/Matisse HD Audio Controller|NoiseTorch Microphone for Starship/Matisse HD Audio Controller Source
```

When selecting this input in the GUI, the recording immediately fails with the message

> Failed to save video. Either your graphics card doesn't support GPU Screen Recorder with the settings you used or you don't have enough disk space to record a video. Run GPU Screen Recorder from the terminal to see more information when this failure happens

When I remove this audio device from the audio track, everything works perfectly fine.

As a side note, even the CLI requires a workaround to get this to work.

`gpu-screen-recorder -w screen -a "NoiseTorch Microphone for Starship/Matisse HD Audio Controller" -o "$HOME/Videos/video.mp4"` fails with:

> Error: Audio input device 'Matisse HD Audio Controller' is not a valid audio device, expected one of: ...

Seems like the option to use a name prefix with a `/` causes a problem here.

When I instead use `gpu-screen-recorder -a "mic/NoiseTorch Microphone for Starship/Matisse HD Audio Controller" ...`, everything works fine.

**To Reproduce**
See above.

**Desktop**
 - Wayland
- Desktop environment/Window Manager: KDE Plasma 6.2.1/KWin (normal KDE setup)
 - Distro: Arch Linux
 - GPU: AMD Radeon RX 6900 XT
 - Version (latest flatpak version, aur or source): Latest AUR

**Comment by dec05eba** [comment]
Ah, virtual audio device.. it ignores the typical name pattern of real audio devices :(
I'll see how I can best fix this..

**Comment by dec05eba** [comment]
It should be fixed now. The change has been pushed to aur. Please update and test that it works for you.

**Comment by FreezyLemon** [comment]
Just updated and it works now. Thanks for the quick response!
