### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JustCauseWhyNot** [dec05eba/gpu-screen-recorder-issues#61]
**Describe the bug**

Simultaneous recording & replay not working. 
![2024-10-29_22-15](https://github.com/user-attachments/assets/ad173dcc-7723-4252-8d44-c028594cd62f)

**To Reproduce**
The GPU Screen Recorder command you ran or if you used the GUI version then describe which options you used.
Here's an image of the recorder options 
![2024-10-29_22-16](https://github.com/user-attachments/assets/40c13b0c-1f21-4b4a-a186-063bd62fbc50). I do have [disk space](https://paste.gentoo.zip/D5loLAKH), and I've got 30GiB of free ram

**Screenshots**
added above.

**Desktop (please complete the following information):**
 - X11 or Wayland: x11
 - Desktop environment/Window Manager: dwm
 - Distro: gentoo
 - GPU: rtx 4070 super
 - Version (latest flatpak version, aur or source): source 4.2.4

**Additional context**

> Add any other context about the problem here, such as terminal output of running GPU Screen Recorder and if the issue isn't related to audio then please run `sudo drm_info > log.txt` and attach that log.txt file in this bug report. drm_info can be installed from your package manager or from https://gitlab.freedesktop.org/emersion/drm_info.

[drm_info](https://paste.gentoo.zip/rWxnyeZu)

> Attach a video that shows the issue (if applicable), in raw form as output by GPU Screen Recorder or a losslessly cut version of it (you can use https://flathub.org/apps/org.gnome.gitlab.YaLTeR.VideoTrimmer for example to do this). 

wouldn't add anything.

> Which game did you run while recording (if any) and does the issue also happen if you only record your desktop?

n/a

> Does the issue also happen if you use obs studio instead with equivalent settings (video encoding settings and audio codec settings. Nvenc on nvidia and vaapi on amd/intel and same video/audio codec)?

I've not tried obs.

> If you have an issue with audio make sure you are not using pulseaudio/pipewire audio processing software such as EasyEffects.
If you are setting any amd/intel/nvidia/mesa/vaapi/pulseaudio/pipewire environment variables then please list those. 

Here's [printenv](https://paste.gentoo.zip/H0Rwupgv)

- [**Y**] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [**N**] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
Did you run the program (the gui) from the terminal as suggested in the error message? it should mention more information about why it failed. Do that and post the terminal output here. My guess it that it's an artificial nvidia driver limitation for consumer grade nvidia gpus.

**Comment by JustCauseWhyNot** [comment]
I'm dumb. Idk why but I only thought about the terminal coamad to bs be run from terminal. Not the gui one also possible. I'll post output soon.

**Comment by JustCauseWhyNot** [comment]
Here's output from replay

<details>

<summary> replay </summary>

```
❯ gpu-screen-recorder-gtk

(gpu-screen-recorder-gtk:5471): dbind-WARNING **: 15:54:39.446: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0: Permission denied
Notification: title: GPU Screen Recorder, body: Started replay
gsr error: gsr_xnvctrl_load failed: failed to load libXNVCtrl.so.0, error: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
gsr warning: gsr_cuda_load: failed to load xnvctrl, failed to overclock memory transfer rate
[av1_nvenc @ 0x1f66d9c0] ignoring invalid SAR: 0/0

(gpu-screen-recorder-gtk:5471): libayatana-appindicator-WARNING **: 15:54:44.607: Unable to register object on path '/org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder': An object is already exported for the interface org.kde.StatusNotifierItem at /org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder

(gpu-screen-recorder-gtk:5471): LIBDBUSMENU-GLIB-WARNING **: 15:54:44.607: Unable to register object on bus: An object is already exported for the interface com.canonical.dbusmenu at /org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder/Menu
update fps: 61, damage fps: 61
update fps: 60, damage fps: 60
update fps: 60, damage fps: 60
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
update fps: 60, damage fps: 60
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61

(gpu-screen-recorder-gtk:5471): libayatana-appindicator-WARNING **: 15:54:53.742: Unable to register object on path '/org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder': An object is already exported for the interface org.kde.StatusNotifierItem at /org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder
update fps: 60, damage fps: 60
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
Notification: title: GPU Screen Recorder, body: Stopped replay
Notification: title: GPU Screen Recorder, body: Started replay
gsr error: gsr_xnvctrl_load failed: failed to load libXNVCtrl.so.0, error: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
gsr warning: gsr_cuda_load: failed to load xnvctrl, failed to overclock memory transfer rate
[av1_nvenc @ 0x22a9f200] ignoring invalid SAR: 0/0
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
update fps: 60, damage fps: 60
update fps: 60, damage fps: 60
update fps: 61, damage fps: 61
update fps: 60, damage fps: 60
update fps: 60, damage fps: 60
update fps: 61, damage fps: 61
update fps: 60, damage fps: 60
update fps: 60, damage fps: 60
update fps: 60, damage fps: 60
update fps: 61, damage fps: 61
update fps: 61, damage fps: 61
update fps: 60, damage fps: 60
update fps: 61, damage fps: 61
update fps: 60, damage fps: 60
Notification: title: GPU Screen Recorder, body: Stopped replay
```

</details>

And here's recording output

<details>

<summary> recording </summary>

```
❯ gpu-screen-recorder-gtk

(gpu-screen-recorder-gtk:5978): dbind-WARNING **: 15:55:11.214: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0: Permission denied
Notification: title: GPU Screen Recorder, body: Started recording
gsr error: gsr_capture_nvfbc_start failed: This hardware does not support NvFBC
gsr error: gsr_capture_start failed
Notification: title: GPU Screen Recorder, body: Failed to save video. Either your graphics card doesn't support GPU Screen Recorder with the settings you used or you don't have enough disk space to record a video. Run GPU Screen Recorder from the terminal to see more information when this failure happens

(gpu-screen-recorder-gtk:5978): libayatana-appindicator-WARNING **: 15:55:18.419: Unable to register object on path '/org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder': An object is already exported for the interface org.kde.StatusNotifierItem at /org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder

(gpu-screen-recorder-gtk:5978): LIBDBUSMENU-GLIB-WARNING **: 15:55:18.419: Unable to register object on bus: An object is already exported for the interface com.canonical.dbusmenu at /org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder/Menu

(gpu-screen-recorder-gtk:5978): libayatana-appindicator-WARNING **: 15:55:19.482: Unable to register object on path '/org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder': An object is already exported for the interface org.kde.StatusNotifierItem at /org/ayatana/NotificationItem/com_dec05eba_gpu_screen_recorder

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_combo_box_get_active_iter: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_spin_button_get_value_as_int: assertion 'GTK_IS_SPIN_BUTTON (spin_button)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_spin_button_get_value_as_int: assertion 'GTK_IS_SPIN_BUTTON (spin_button)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_spin_button_get_value_as_int: assertion 'GTK_IS_SPIN_BUTTON (spin_button)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_spin_button_get_value_as_int: assertion 'GTK_IS_SPIN_BUTTON (spin_button)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_spin_button_get_value_as_int: assertion 'GTK_IS_SPIN_BUTTON (spin_button)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_spin_button_get_value_as_int: assertion 'GTK_IS_SPIN_BUTTON (spin_button)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_toggle_button_get_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_toggle_button_get_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(gpu-screen-recorder-gtk:5978): Gtk-CRITICAL **: 15:55:24.222: gtk_combo_box_get_active_id: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed
zsh: segmentation fault (core dumped)  gpu-screen-recorder-gtk
```
</details>

**Comment by dec05eba** [comment]
>This hardware does not support NvFBC

I guess thats the artificial limitation, that it only allows one monitor capture session at a time. Try recording a window instead of a monitor and it should work. Or record on wayland. Nvidia has dumb limitations. Using this https://github.com/keylase/nvidia-patch might remove the limitation.
There is a planned feature in gpu screen recorder to allow start recording in the existing replay capture, so you dont hit this limitation and it wont have to capture the screen twice.

**Comment by JustCauseWhyNot** [comment]
Thank you for the help. And the planned feature sounds nice. Looking forward too it. I'm just trying to be able to save like 30s clips, and a long recording if an interesting match happens.
