### ISSUE TITLE
[BUG] No windows icon for gpu-screen-recorder-gtk on KDE

### ISSUE THREAD

**Issue by OlegAckbar** [dec05eba/gpu-screen-recorder-issues#63]
**Describe the bug**
GPU Screen Recorder GTK application has no window icon on KDE.

**To Reproduce**
Open GPU Screen Recorder GTK.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/f6f838c8-18ed-4af5-88a8-0de2feeea45d)

**Desktop (please complete the following information):**
- gpu-screen-recorder-gtk-git r402.ee137ee-1 from AUR
- Operating System: Arch Linux 
- KDE Plasma Version: 6.2.2
- KDE Frameworks Version: 6.7.0
- Qt Version: 6.8.0
- Kernel Version: 6.11.6-2-cachyos (64-bit)
- Graphics Platform: Wayland
- Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
- Memory: 15.6 ГиБ of RAM
- Graphics Processor: AMD Radeon RX 6700 XT

**Comment by dec05eba** [comment]
Uhh no application has window icons for me on kde plasma so I cant check this myself. But how do you start the application? from the desktop/start menu icon? also have you rebooted after installing gpu screen recorder gtk?

**Comment by dec05eba** [comment]
I pushed a change to gpu screen recorder gtk on aur, you can update to the latest version and see if there is a difference as well if none of the above works. I dont know if it makes a difference on wayland.

**Comment by OlegAckbar** [comment]
I'm starting from either kickoff application launcher or krunner: neither gives me proper Window icon.
The main problem is that application window doesn't have appid/desktopfilename properly set (it should be com.dec05eba.gpu_screen_recorder) and Wayland compositors relies on appid to give applications window icons. `gtk_window_set_icon_name` just doesn't work under Wayland.
![image](https://github.com/user-attachments/assets/d7be46aa-1a64-4c34-8bec-7ca2432c82bf)

**Comment by dec05eba** [comment]
huh, the app id is com.dec05eba.gpu_screen_recorder and the desktop file name is com.dec05eba.gpu_screen_recorder(.desktop)

**Comment by dec05eba** [comment]
I pushed a change to aur that might fix it. Can you update and try? I have no idea why window icons dont display for me (they dont display even in xfce).
Btw, are you the guy posting webms on /lgg/?

**Comment by OlegAckbar** [comment]
Yep, that did the tricks.
And yes, it's me who posting webms.
![изображение](https://github.com/user-attachments/assets/a79ffaa0-6be1-45c9-9beb-2ee8a9afe179)

**Comment by dec05eba** [comment]
Thanks!
