### ISSUE TITLE
[BUG] Program crashes at startup

### ISSUE THREAD

**Issue by DJXJD** [dec05eba/gpu-screen-recorder-issues#64]
**Describe the bug**
gpu-screen-recorder started crashing at startup this morning. I've never had this particular issue before.

**To Reproduce**
The following commands both produce the same issue:
`gpu-screen-recorder -w DP-1 -f 60 -a "default_output|default_input" -r 300 -c mkv -o ~/Videos/Clips -df yes -v no`
`gpu-screen-recorder -w DP-1 -f 60 -a "default_output|default_input" -r 300 -c mkv -k hevc -o ~/Videos/Clips -df yes -v no`

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: Hyprland
 - Distro: Arch
 - GPU: EVGA RTX 3080 Ti FTW3
 - Version (latest flatpak version, aur or source): AUR

**Additional context**
Terminal output:
```
[David@DJXJDArch ~]$ gpu-screen-recorder -w DP-1 -f 60 -a "default_output|default_input" -r 300 -c mkv -o ~/Videos/Clips -df yes -v no
Info: using h264 encoder because a codec was not specified
gsr info: gsr_kms_client_init: setting up connection to /usr/bin/gsr-kms-server
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[h264_nvenc @ 0x5d4a69b41200] [Eval @ 0x7fff450e1e60] Undefined constant or missing '(' in 'high'
[h264_nvenc @ 0x5d4a69b41200] Unable to parse option value "high"
[h264_nvenc @ 0x5d4a69b41200] Error setting option profile to value high.
Error: Could not open video codec: Invalid argument
[David@DJXJDArch ~]$ gpu-screen-recorder -w DP-1 -f 60 -a "default_output|default_input" -r 300 -c mkv -k hevc -o ~/Videos/Clips -df yes -v no
gsr info: gsr_kms_client_init: setting up connection to /usr/bin/gsr-kms-server
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[hevc_nvenc @ 0x62a7f6179e40] [Eval @ 0x7ffea5b8b720] Undefined constant or missing '(' in 'main'
[hevc_nvenc @ 0x62a7f6179e40] Unable to parse option value "main"
[hevc_nvenc @ 0x62a7f6179e40] Error setting option profile to value main.
Error: Could not open video codec: Invalid argument
```
[log.txt](https://github.com/user-attachments/files/17677895/log.txt)

>Does the issue also happen if you use obs studio instead with equivalent settings (video encoding settings and audio codec settings. Nvenc on nvidia and vaapi on amd/intel and same video/audio codec)?

I am able to record video in obs using h264_nvenc or hevc_nvenc, and opus, without issue.

>If you are setting any amd/intel/nvidia/mesa/vaapi/pulseaudio/pipewire environment variables then please list those.

Nvidia env vars from my Hyprland config:
```
# Nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct # VA-API
```

**Comment by dec05eba** [comment]
Looks like ffmpeg update broke it. Im working on it

**Comment by dec05eba** [comment]
Actually, can you try reinstalling gpu screen recorder?

**Comment by DJXJD** [comment]
Rebuilding did indeed fix the issue! Thank you very much!
