### ISSUE TITLE
[BUG] Black screen

### ISSUE THREAD

**Issue by DrWarpMan** [dec05eba/gpu-screen-recorder-issues#66]
**Describe the bug**
[This commit](https://git.dec05eba.com/gpu-screen-recorder/commit/?id=f1b49793658d42cc7dd53be757f34ec6437d0517) has broken recording for me, and now the output of the recording is a black screen. Audio works.

**To Reproduce**
This is how I am running the recorder (replay mode):
```bash
gpu-screen-recorder \
    -w screen \
    -f 60 \
    -r 600 \
    -c mp4 \
    -o "${HOME}/Videos" 
```

**Desktop:**
 - X11 or Wayland: **X11**
- Desktop environment/Window Manager: **LeftWM**
 - Distro: **Arch Linux**
 - GPU: **NVIDIA GeForce GTX 1650**
 - Version: Not working since [f1b49793658d42cc7dd53be757f34ec6437d0517](https://git.dec05eba.com/gpu-screen-recorder/commit/?id=f1b49793658d42cc7dd53be757f34ec6437d0517), the [commit before](https://git.dec05eba.com/gpu-screen-recorder/commit/?id=e647d0c4bcbd7001b81a7a3618987e220615f2d6) works fine.

**Additional context**
- [drm_info-log.txt](https://github.com/user-attachments/files/17729222/drm_info-log.txt)
- The terminal output shows no  errors, it's the same output from broken and working versions of the program.
- _Yes_, I played the video with the command `mpv --no-config video.mp4`
- _No, I don't_ use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
Thanks for finding the commit with the issue and reporting it! It should be fixed now, the fix has been pushed to git and aur. Please re-open if it's still an issue after updating.
This was an issue specifically on nvidia on x11.
