### ISSUE TITLE
[BUG] Window doesn't resize to content

### ISSUE THREAD

**Issue by ChildishGiant** [dec05eba/gpu-screen-recorder-issues#67]
**Describe the bug**
When an audio channel is added the content of the window begins to scroll instead of the window resizing to fit the content. While the content is still usable it's somewhat confusing to the end user and I imagine unintended.

**To Reproduce**
For me this is reproducible by adding an audio channel as my GPU has a very long audio interface name.

**Screenshots**
[gpu-recorder-width.webm](https://github.com/user-attachments/assets/e84f3d99-b3fe-4847-9f8f-d19217419185)

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: GNOME 46.5
 - Distro: Manjaro
 - GPU: Radeon RX480
 - Version (latest flatpak version, aur or source): 4.3.0 flatpak stable

**Additional context**
Video recorded with OBS and re-encoded to webm, I don't think that's too relevant though
- [x] I played the video with the command `mpv --no-config video.mp4` (if applicable)

**Comment by dec05eba** [comment]
Yeah the ui sizing isn't good right now. I'll see what I can do with it. The entire gtk ui will be replaced soon as well.

**Comment by dec05eba** [comment]
It has been fixed now. The fix will be available in flatpak in a few hours when flathub updates it.
