### ISSUE TITLE
[BUG] Regression: Recording from portals is broken.

### ISSUE THREAD

**Issue by jackmio32** [dec05eba/gpu-screen-recorder-issues#68]
**Describe the bug**
I decided to update gpu-screen-recorder because why not, but after doing git pull and recompiling, recording from portals is broken with a corrupted video output and massive log spam.

**To Reproduce**
I ran it with all of the default settings specified for the systemd unit, except for `-w portal`

**Screenshots**
![A screenshot from a broken recording](https://github.com/user-attachments/assets/f8f482af-abff-4e92-9e4f-9ec46d2a2946)

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: KDE Plasma 5.27.11
 - Distro: Kubuntu 24.04
 - GPU: RX 6800
 - Version (latest flatpak version, aur or source): Compiled from source

**Additional context**
DRM info: [drm_info.txt](https://github.com/user-attachments/files/17836063/log.txt)
GPU Screen Recorder's systemd unit log: [journalctloutput.txt](https://github.com/user-attachments/files/17836367/journalctloutput.txt)
I cannot attach a full quality video, as the file is too large even when shortened to 1/2 a second.

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
That error comes from the driver itself.. hmm. Did you try if the same thing happens with obs if you enable vaapi in obs and use portal capture?

**Comment by dec05eba** [comment]
Yes -w screen. I tried to reproduce it myself but couldn't. Your systemd config isn't just -w portal, it also includes hevc codec. Please stop the systemd service and record like this instead:
`gpu-screen-recorder -w portal -f 60 -o video.mp4`
and also try:
`gpu-screen-recorder -w screen -f 60 -o video.mp4`.

I cant reproduce the issue myself on arch on amd.

**Comment by dec05eba** [comment]
Ok hmm. Can you do git checkout on the commit you were on previous to reinstall gpu scfreen recorder try recording again? and which commit was that? if you remember

**Comment by dec05eba** [comment]
Oh thats very old..

**Comment by dec05eba** [comment]
Yeah I understand, but in this case it might not have failed when it should have and continued. There are cases when the amd gpu driver just fails without reporting things as a failure.

Anyways, I pushed a commit. Can you pull the latest changes, reinstall and try recording with portal again?

**Comment by dec05eba** [comment]
Well damn.. hmm, not sure what to do about that. I want to keep the code that was before for performance reasons. So its the amd driver that craps itself in some cases.. it looks like it completely breaks vaapi

**Comment by dec05eba** [comment]
Ok, can you try one last thing? for git pull and reinstall again but this time record with:
`gpu-screen-recorder -w portal -f 60 -cursor no -o video.mp4`

**Comment by dec05eba** [comment]
If possible can you try the flatpak version gpu screen recorder? flatpak includes a newer version of mesa which possibly fixes the issue you have. I want to see if its specifically an issue with your mesa version on kubuntu.

**Comment by dec05eba** [comment]
The test commit I pushed before that you tested that works is pretty much the same as the old commit, it's just one difference. Since that works in the flatpak then its pretty much guaranteed a bug in the amd driver (mesa) on your system (or possibly ffmpeg version). Can you run `ffmpeg -version > ffmpeg.log` and `eglinfo > eglinfo.log` and upload the ffmpeg.lgo and eglinfo.log files here? I can add an exception in the code that if the mesa version is old then it uses the old method which doesn't cause the amd driver bug.

**Comment by dec05eba** [comment]
AMD drivers have tons of bugs, so this is nothing unusual. Just have to add another exception for known broken versions.

**Comment by dec05eba** [comment]
Hmm your mesa version isn't that old, it's from 2024-06-06. Your ffmpeg version however is from 2023-12-30.

**Comment by dec05eba** [comment]
Ok thanks. I'll add a version check then :+1:

**Comment by dec05eba** [comment]
I added a version check now. Can you update to the latest version of gpu screen recorder and try portal capture? it should work on both the old and new version of mesa driver now.

**Comment by dec05eba** [comment]
The issue has been fixed. Re-open this issue if it doesn't work with the latest version.
