### ISSUE TITLE
[BUG] Cant start recording cause audio and h264 error

### ISSUE THREAD

**Issue by Keqwerty** [dec05eba/gpu-screen-recorder-issues#69]
**Describe the bug**
Cant start recording cause Error: Audio input device 'device:default_output' is not a valid audio device

**To Reproduce**
Just click start recording

**Screenshots**
![image](https://github.com/user-attachments/assets/b175136f-de5e-4977-b6df-384e5361a829)

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: GNOME 47
 - Distro: Arch Linux
 - GPU: NVIDIA RTX 3060 12GB
 - Version (latest flatpak version, aur or source): source, 4.3.2

**Additional context**
Tried with different audio devices but result is same.
Full log:

```
info: running command: gpu-screen-recorder -w DP-0 -c mp4 -k h264 -ac opus -f 60 -cursor yes -restore-portal-session yes -cr full -encoder gpu -o /home/keqwerty/Videos/Video_2024-11-22_00-53-56.mp4 -q high -a device:default_output
Error: Audio input device 'device:default_output' is not a valid audio device, expected one of:
    default_output (Default output)
    default_input (Default input)
    alsa_input.usb-3142_Fifine_Microphone-00.mono-fallback (Fifine Microphone Mono)
    alsa_output.usb-TEMPOTEC_TempoTec_HD_USB_AUDIO-01.analog-stereo.monitor (Monitor of TempoTec HD USB AUDIO Analog Stereo)
    alsa_output.pci-0000_01_00.1.hdmi-stereo.2.monitor (Monitor of GA104 High Definition Audio Controller Digital Stereo (HDMI))
Notification: title: GPU Screen Recorder, body: Failed to save video. Either your graphics card doesn't support GPU Screen Recorder with the settings you used or you don't have enough disk space to record a video. Start this GPU Screen Recorder GUI application from the terminal to see more information when this failure happens
```

**Comment by dec05eba** [comment]
It looks like you are not using the latest version. the aur package was renamed from gpu-screen-recorder-git to gpu-screen-recorder, same for gpu-screen-recorder-gtk-git that was renamed to gpu-screen-recorder-gtk.

**Comment by Keqwerty** [comment]
i am installed gpu-screen-recorder-gtk from aur (program title says 4.3.1 version) but error still there

**Comment by dec05eba** [comment]
you need to install gpu-screen-recorder as well

**Comment by Keqwerty** [comment]
i tried source and aur version

**Comment by dec05eba** [comment]
Run gpu-screen-recorder --version and post output

**Comment by dec05eba** [comment]
Run `gpu-screen-recorder -w screen -f 60 -a device:default_output -o video.mp4` and tell me the output

**Comment by Keqwerty** [comment]
> Oh you are using source. You need to install updated gpu screen recorder as well then. The ui uses gpu-screen-recorder command line tool so they both need to be the same version.

As it turned out I had a debug file conflict and the new version of gpu-screen-recorder would not install. I deleted these files via sudo rm and the package installed and the video started recording correctly with audio and stuff.
