### ISSUE TITLE
[BUG] App audio sinks are not removed if gsr is forcefully killed

### ISSUE THREAD

**Issue by GenocideStomper** [dec05eba/gpu-screen-recorder-issues#72]
**Describe the bug**
When running GSR with audio flags that combine apps (and maybe devices), such as `-a 'gsr-discord/app:WEBRTC VoiceEngine|app:Chromium'`, and then stopping the recording, GSR leaves behind items in Helvum or when running `pw-link -Io`
Every additional pipe would leave another object behind.

Additionally `prefix/` name doesn't seem to show up anymore in Helvum / `pw-link`.

**To Reproduce**
Run GSR with `-a 'gsr-discord/app:WEBRTC VoiceEngine|app:Chromium'`

**Screenshots**
![image](https://github.com/user-attachments/assets/8a1b995e-4446-4663-9c7c-0139a04ffda7)
```
$ killall gpu-screen-recorder
$ pw-link -Io
...
 107 gsr-combined-a1ikNWyc:monitor_FL
  96 gsr-combined-a1ikNWyc:monitor_FR
  81 gsr-combined-9DbIpOj4:monitor_FL
  90 gsr-combined-9DbIpOj4:monitor_FR
 162 gsr-combined-WZROCEWu:monitor_FL
 166 gsr-combined-WZROCEWu:monitor_FR
 168 gsr-combined-H4McYERE:monitor_FL
 108 gsr-combined-H4McYERE:monitor_FR
 124 gsr-combined-JaN1WdzJ:monitor_FL
 126 gsr-combined-JaN1WdzJ:monitor_FR
...
```

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: KDE Plasma 6
 - Distro: endeavourOS
 - GPU: Nvidia GTX 1080
 - Version (latest flatpak version, aur or source): AUR gpu-screen-recorder-r912.0ae3c1f-1 , v4.3.3

**Additional context**
Low priority issue as the audio stuff works, I just don't know if there's a minimal performance impact when leaving those sinks behind.

**Comment by dec05eba** [comment]
You have to stop gpu-screen-recorder cleanly with `killall -SIGINT gpu-screen-recorder` to allow it to remove the sink. Unfortunately there doesn't seem to be a way to fix this with the pulseaudio interface. I'll see sometime later if I can use pipewire instead which should have the option to make it automatically clean when the program is killed as well

**Comment by dec05eba** [comment]
Fixed. The fix is in git and aur (version r918.175ed79)

**Comment by GenocideStomper** [comment]
Thank you very much, you're awesome! And I'll change my killall command in my scripts.
