### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by itomilin** [dec05eba/gpu-screen-recorder-issues#73]
**Describe the bug**
I'm launching the application with AV1 options, but the log says that AV1 is not supported. What am I doing wrong?

**To Reproduce**
gpu-screen-recorder -w screen -k av1 -q medium -c mkv -f 60 -o ./video.mkv

**Screenshots**
![image](https://github.com/user-attachments/assets/7767e806-ab9e-4da3-8822-dad79aaa1203)

log msg:
`
gpu-screen-recorder -w screen -k av1 -q medium -c mkv -f 60 -o ./video.mkv
Warning: selected video codec av1 is not supported, trying h264 instead
gsr info: gsr_kms_client_init: setting up connection to /usr/bin/gsr-kms-server
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[h264_vaapi @ 0x558dcb13d800] ignoring invalid SAR: 0/0
[h264_vaapi @ 0x558dcb13d800] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
update fps: 61, damage fps: 61
update fps: 60, damage fps: 60
`

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: DWM
 - Distro: Linux debian 6.11.5+bpo-amd64
 - GPU: [Radeon RX 7900 XTX
 - Version (latest flatpak version, aur or source): build from src v4.3.4

**Comment by dec05eba** [comment]
Install vainfo and run `vainfo` and post the output here.

**Comment by itomilin** [comment]
![image](https://github.com/user-attachments/assets/fcb9bebc-648c-42a3-ac6f-e44d739e01fc)


`
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 24.2.4-1~bpo12+1 for AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 15.0.6, DRM 3.59, 6.11.5+bpo-amd64)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSlice
      VAProfileNone                   : VAEntrypointVideoProc

`

**Comment by dec05eba** [comment]
>LIBVA_DRIVER_NAME
run without setting that. gpu screen recorder unsets that

**Comment by itomilin** [comment]
![image](https://github.com/user-attachments/assets/b1dc21f1-7190-4357-bce7-5edb12963bd7)

**Comment by dec05eba** [comment]
Can you run `gpu-screen-recorder --info`?

**Comment by itomilin** [comment]
section=system_info
display_server|x11
supports_app_audio|yes
is_steam_deck|no
section=gpu_info
vendor|amd
card_path|/dev/dri/card0
section=video_codecs
h264
h264_software
hevc
hevc_10bit
section=capture_options
window
focused
DisplayPort-0|3840x2160

**Comment by dec05eba** [comment]
Hmm.. can you then also run `vainfo --display drm --device /dev/dri/card0`

**Comment by itomilin** [comment]
> vainfo --display drm --device /dev/dri/card0
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 24.2.4-1~bpo12+1 for AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 15.0.6, DRM 3.59, 6.11.5+bpo-amd64)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSlice
      VAProfileNone                   : VAEntrypointVideoProc

**Comment by dec05eba** [comment]
Ok maybe your ffmpeg version is too old then. Can you run `ffmpeg -h encoder=av1_vaapi`?

**Comment by itomilin** [comment]
>ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
 Codec 'av1_vaapi' is not recognized by FFmpeg.
 

Yes
ffmpeg is too old, but not for debian
 
I ran the same cmd on another machine (arch distro + ffmpeg 7.1) and everything is fine

**Comment by dec05eba** [comment]
ow thats a very old version yeah. AV1 requires a relatively recent version of ffmpeg
